/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/lcm/v1/issuers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIssuers"];
        put?: never;
        post: operations["createIssuer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/issuers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIssuer"];
        put: operations["updateIssuer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/issuers/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteIssuer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/dns-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDnsProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCertificates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/acme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["obtainAcmeCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCertificate"];
        put: operations["updateCertificate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/{id}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Details decoded from the stored certificate bytes (crypto/x509), never from the record columns or the request. An undecodable certificate answers 200 with available=false, error=details_unavailable and a reason. No key material is returned. */
        get: operations["getCertificateDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadCertificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/{id}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadCertificateKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/{id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["renewCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/{id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deployCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/certificates/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRequests"];
        put?: never;
        post: operations["createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/bootstrap-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBootstrapBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/trust-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTrustBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/revocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRevocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/crl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/deployment-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDeploymentTargets"];
        put?: never;
        post: operations["createDeploymentTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/installed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInstalled"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSecrets"];
        put?: never;
        post: operations["createSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/secrets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateSecret"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/secrets/{id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/secrets/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWebhooks"];
        put?: never;
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/webhooks/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGrants"];
        put?: never;
        post: operations["grant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/grants/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/access/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["checkAccess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/access/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["effectivePermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/access/accessible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccessible"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/backup/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exportBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Without from/to the page covers the last 7 days (to = now, from = to - 7d); the total is exact within the window. The range may span at most 90 days (wider: 422 validation_failed, param from). The legacy cursor/limit shape uses the same window. */
        get: operations["auditTrail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lcm/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            reason: string;
            detail?: Record<string, never>;
        };
        Name: string;
        SpiffeId: string;
        Permissions: {
            read?: boolean;
            write?: boolean;
            delete?: boolean;
            share?: boolean;
            use?: boolean;
        };
        IssuerInput: {
            name: components["schemas"]["Name"];
            /** @enum {string} */
            type: "self_signed" | "acme";
            trust_domain: string;
            /** @default false */
            is_default: boolean;
            /** @description non-secret config: key type, validity ceiling, ACME directory/email/dns_provider */
            settings?: Record<string, never>;
            /** @description write-only: ACME account key / DNS credentials; "__set__" or omitted keeps stored values */
            secrets?: Record<string, never>;
        };
        Issuer: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            type?: "self_signed" | "acme";
            trust_domain?: string;
            is_default?: boolean;
            enabled?: boolean;
            settings?: Record<string, never>;
            certificate_count?: number;
            created_by?: string;
            /** Format: date-time */
            created_at?: string;
            permissions?: components["schemas"]["Permissions"];
        };
        IssueInput: {
            /**
             * Format: uuid
             * @description default issuer for the trust domain when omitted
             */
            issuer_id?: string;
            spiffe_id: components["schemas"]["SpiffeId"];
            /** @description when set, the module signs it; otherwise it generates the key pair */
            csr_pem?: string;
            subject?: string;
            dns_sans?: string[];
            validity_seconds?: number;
            /**
             * @description return the generated private key once (only when csr_pem is omitted)
             * @default false
             */
            deliver_key: boolean;
        };
        Certificate: {
            /** Format: uuid */
            id?: string;
            serial?: string;
            spiffe_id?: string;
            subject?: string;
            /** Format: uuid */
            issuer_id?: string;
            sans?: string[];
            /** Format: date-time */
            not_before?: string;
            /** Format: date-time */
            not_after?: string;
            fingerprint_sha256?: string;
            /** @enum {string} */
            status?: "active" | "expiring" | "expired" | "revoked";
            owner?: string;
            /** Format: date-time */
            created_at?: string;
            permissions?: components["schemas"]["Permissions"];
        };
        CertificateName: {
            /** @description RFC 2253 distinguished name */
            dn: string;
            cn: string;
        };
        CertificateChainEntry: {
            subject: components["schemas"]["CertificateName"];
            issuer: components["schemas"]["CertificateName"];
            /** Format: date-time */
            not_after: string;
            /** @description colon-separated upper-case hex of the DER SHA-256 */
            fingerprint_sha256: string;
        };
        CertificateDetails: {
            subject: components["schemas"]["CertificateName"];
            issuer: components["schemas"]["CertificateName"];
            self_signed: boolean;
            /** @description colon-separated upper-case hex */
            serial: string;
            version: number;
            validity: {
                /** Format: date-time */
                not_before: string;
                /** Format: date-time */
                not_after: string;
                /**
                 * @description computed from the certificate dates
                 * @enum {string}
                 */
                status: "not_yet_valid" | "valid" | "expired";
                /** @description whole days until not_after (negative once expired) */
                days_remaining: number;
            };
            sans: {
                dns: string[];
                ip: string[];
                /** @description all URI SANs, SPIFFE IDs included */
                uri: string[];
                spiffe: string[];
                email: string[];
            };
            public_key: {
                algorithm: string;
                size?: number;
                curve?: string;
            };
            signature_algorithm: string;
            key_usage: string[];
            ext_key_usage: string[];
            basic_constraints: {
                present: boolean;
                ca: boolean;
                /** @description absent when unconstrained */
                path_len?: number;
            };
            subject_key_id?: string;
            authority_key_id?: string;
            crl_distribution_points: string[];
            ocsp_servers: string[];
            issuing_certificate_urls: string[];
            fingerprints: {
                sha256: string;
                sha1: string;
            };
            chain: components["schemas"]["CertificateChainEntry"][];
            /** @description set when a stored chain certificate could not be parsed */
            chain_error?: string;
        };
        CertificateDetailsResult: {
            available: boolean;
            /** @enum {string} */
            source: "certificate";
            /** @enum {string} */
            error?: "details_unavailable";
            reason?: string;
            details?: components["schemas"]["CertificateDetails"];
        };
        CertificateBundle: {
            certificate?: components["schemas"]["Certificate"];
            cert_pem?: string;
            chain_pem?: string;
            bundle_pem?: string;
            /** @description present exactly once when the module generated the key */
            key_pem?: string;
        };
        GrantInput: {
            /** @enum {string} */
            resource_type: "certificate" | "issuer";
            /** Format: uuid */
            resource_id: string;
            /** @enum {string} */
            subject_type: "user" | "role" | "tenant";
            subject_id?: string;
            /** @enum {string} */
            relation: "owner" | "editor" | "viewer" | "sharer";
            /** Format: date-time */
            expires_at?: string | null;
        };
        SecretInput: {
            name: components["schemas"]["Name"];
            /** @enum {string} */
            kind: "acme_account" | "dns_credential";
            /** @description write-only credential fields; never returned */
            value: Record<string, never>;
        };
    };
    responses: never;
    parameters: {
        csrf: string;
        id: string;
        cursor: string;
        /** @description legacy cursor style; 50 when omitted */
        limit: number;
        page: number;
        pageSize: number;
        order: "asc" | "desc";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listIssuers: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "name" | "type" | "trust_domain" | "created_at";
                order?: components["parameters"]["order"];
                cursor?: components["parameters"]["cursor"];
                /** @description legacy cursor style; 50 when omitted */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of the issuers the caller may read (total counts only those) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed {param} */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createIssuer: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuerInput"];
            };
        };
        responses: {
            /** @description created; a self-signed issuer generates its CA; creator becomes owner */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description name or default taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIssuer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description issuer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateIssuer: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuerInput"];
            };
        };
        responses: {
            /** @description updated; secrets "__set__"/omitted keep stored values; type cannot change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteIssuer: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted with its grants */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description conflict: certificates reference it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDnsProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description [{name, display_name, fields:[{key,label,secret,required}]}] */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCertificates: {
        parameters: {
            query?: {
                issuer_id?: string;
                spiffe_id?: string;
                status?: "active" | "expiring" | "expired" | "revoked";
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "identity" | "issuer" | "kind" | "status" | "not_before" | "not_after" | "created_at";
                order?: components["parameters"]["order"];
                cursor?: components["parameters"]["cursor"];
                /** @description legacy cursor style; 50 when omitted */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of the certificates the caller may read (metadata only; total counts only those) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed {param} */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issueCertificate: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueInput"];
            };
        };
        responses: {
            /** @description issuance accepted; the outcome arrives over SSE (certificate.issued | certificate.failed). A generated key is retained and downloadable */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description forbidden: no use on the issuer or not entitled to the SPIFFE id */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed (CSR/SPIFFE id/validity) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtainAcmeCertificate: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    issuer_id: string;
                    domains: string[];
                    csr_pem?: string;
                    deliver_key?: boolean;
                    auto_renew?: boolean;
                };
            };
        };
        responses: {
            /** @description order accepted { status: processing, domains, request_id }; recorded as a generic certificate request (processing -> issued | failed with the reason); the outcome also arrives over SSE (certificate.issued | certificate.failed) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not entitled to the issuer */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed (issuer, or a malformed / redundant domain, named in the message) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description certificate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCertificate: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    owner?: string;
                    labels?: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCertificateDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CertificateDetailsResult */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateDetailsResult"];
                };
            };
            /** @description not_found (also when the caller may not read the certificate) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CertificateBundle without key_pem (the key is delivered only at issuance) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadCertificateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The retained private key { key_pem } for a generic certificate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renewCertificate: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CertificateBundle for the renewed certificate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeCertificate: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description revoked; serial added to the CRL and revocation feed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deployCertificate: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    target_id: string;
                };
            };
        };
        responses: {
            /** @description deployment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCertificate: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRequests: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected" | "issued" | "processing" | "failed";
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "identity" | "kind" | "status" | "created_at";
                order?: components["parameters"]["order"];
                cursor?: components["parameters"]["cursor"];
                /** @description legacy cursor style; 50 when omitted */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of the certificate requests the caller may read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed {param} */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createRequest: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueInput"];
            };
        };
        responses: {
            /** @description pending (or issued when auto-approve is on) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approveRequest: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description approved; issuance job queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not pending */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectRequest: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                status?: "queued" | "processing" | "completed" | "failed";
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "type" | "status" | "attempts" | "run_after" | "created_at";
                order?: components["parameters"]["order"];
                cursor?: components["parameters"]["cursor"];
                /** @description legacy cursor style; 50 when omitted */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of the jobs the caller may read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed {param} */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description job status + result reference */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retryJob: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description re-queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not failed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    spiffe_id: components["schemas"]["SpiffeId"];
                    csr_pem?: string;
                    /** @description auth-minted single-use enrollment token */
                    enrollment_token: string;
                };
            };
        };
        responses: {
            /** @description CertificateBundle (auto-approve) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description pending request (manual approval) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description missing or invalid enrollment token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not entitled to the SPIFFE id */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBootstrapBundle: {
        parameters: {
            query: {
                trust_domain: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description mesh trust roots PEM (public bootstrap anchor) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTrustBundle: {
        parameters: {
            query: {
                trust_domain: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description roots PEM for the trust domain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRevocations: {
        parameters: {
            query?: {
                trust_domain?: string;
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked serials */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCrl: {
        parameters: {
            query: {
                trust_domain: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DER/PEM CRL for the trust domain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDeploymentTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDeploymentTarget: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: components["schemas"]["Name"];
                    /** @enum {string} */
                    kind: "file" | "pull" | "webhook";
                    config?: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listInstalled: {
        parameters: {
            query?: {
                client_id?: string;
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description installed certificates reported by workloads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSecrets: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "name" | "kind" | "created_at";
                order?: components["parameters"]["order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of secret names/kinds; values never read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed {param} */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSecret: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description name taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSecret: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretInput"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotateSecret: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSecret: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description in use by an issuer */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWebhooks: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "name" | "created_at";
                order?: components["parameters"]["order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of endpoints; signing secret never read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed {param} */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: components["schemas"]["Name"];
                    url: string;
                    event_types: string[];
                    secret?: string;
                };
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGrants: {
        parameters: {
            query: {
                resource_type: "certificate" | "issuer";
                resource_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    grant: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantInput"];
            };
        };
        responses: {
            /** @description granted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description relation_above_granter */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeGrant: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    checkAccess: {
        parameters: {
            query: {
                resource_type: "certificate" | "issuer";
                resource_id: string;
                action: "read" | "write" | "delete" | "share" | "use";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description {allowed} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    effectivePermissions: {
        parameters: {
            query: {
                resource_type: "certificate" | "issuer";
                resource_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description {relation, permissions, grants[]} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAccessible: {
        parameters: {
            query: {
                resource_type: "certificate" | "issuer";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ids the caller may access */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream (contracts/stream.md); 429 over 5 streams per person */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportBackup: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    include_credentials?: boolean;
                };
            };
        };
        responses: {
            /** @description backup.schema.json document (attachment); audited as bulk disclosure when include_credentials */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    importBackup: {
        parameters: {
            query?: {
                mode?: "skip" | "overwrite";
            };
            header?: {
                "X-CSRF-Token"?: components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description BackupReport */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description body_too_large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description certificates by status, issuers, jobs, clients, expiring soon, recent errors, open_streams */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auditTrail: {
        parameters: {
            query?: {
                event_type?: string;
                actor_id?: string;
                /** @description Start of the range (RFC 3339). Default: to - 7 days. to - from may not exceed 90 days; a wider range is 422 validation_failed with detail.param "from". */
                from?: string;
                /** @description End of the range (RFC 3339). Default: now. to - from may not exceed 90 days. */
                to?: string;
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "ts";
                order?: components["parameters"]["order"];
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of audit events (no key material; subject_name resolves live subjects) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed {param} */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description {status, database, valkey, scheduler_last_tick, version} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
