// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lcm/v1/lcm.proto

// lcm.v1 is the service-to-service and workload-agent API of the certificate &
// SVID lifecycle module. It is NOT proxied by the gateway: callers are
// authenticated services or workloads on the Freya SPIFFE mTLS channel, policed
// by the module's deploy/policy.yaml. The tenant comes from the request and the
// actor from the verified SPIFFE identity. Responses never carry CA/issuer/DNS
// keys; a workload private key is returned only when the module generated it.

package lcmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateStatus int32

const (
	CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED CertificateStatus = 0
	CertificateStatus_CERTIFICATE_STATUS_ACTIVE      CertificateStatus = 1
	CertificateStatus_CERTIFICATE_STATUS_EXPIRING    CertificateStatus = 2
	CertificateStatus_CERTIFICATE_STATUS_EXPIRED     CertificateStatus = 3
	CertificateStatus_CERTIFICATE_STATUS_REVOKED     CertificateStatus = 4
)

// Enum value maps for CertificateStatus.
var (
	CertificateStatus_name = map[int32]string{
		0: "CERTIFICATE_STATUS_UNSPECIFIED",
		1: "CERTIFICATE_STATUS_ACTIVE",
		2: "CERTIFICATE_STATUS_EXPIRING",
		3: "CERTIFICATE_STATUS_EXPIRED",
		4: "CERTIFICATE_STATUS_REVOKED",
	}
	CertificateStatus_value = map[string]int32{
		"CERTIFICATE_STATUS_UNSPECIFIED": 0,
		"CERTIFICATE_STATUS_ACTIVE":      1,
		"CERTIFICATE_STATUS_EXPIRING":    2,
		"CERTIFICATE_STATUS_EXPIRED":     3,
		"CERTIFICATE_STATUS_REVOKED":     4,
	}
)

func (x CertificateStatus) Enum() *CertificateStatus {
	p := new(CertificateStatus)
	*p = x
	return p
}

func (x CertificateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lcm_v1_lcm_proto_enumTypes[0].Descriptor()
}

func (CertificateStatus) Type() protoreflect.EnumType {
	return &file_lcm_v1_lcm_proto_enumTypes[0]
}

func (x CertificateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateStatus.Descriptor instead.
func (CertificateStatus) EnumDescriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{0}
}

type Certificate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Serial            string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	SpiffeId          string                 `protobuf:"bytes,3,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	Subject           string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	IssuerId          string                 `protobuf:"bytes,5,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Sans              []string               `protobuf:"bytes,6,rep,name=sans,proto3" json:"sans,omitempty"`
	NotBefore         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	FingerprintSha256 string                 `protobuf:"bytes,9,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3" json:"fingerprint_sha256,omitempty"`
	Status            CertificateStatus      `protobuf:"varint,10,opt,name=status,proto3,enum=lcm.v1.CertificateStatus" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{0}
}

func (x *Certificate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Certificate) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Certificate) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *Certificate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Certificate) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *Certificate) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *Certificate) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *Certificate) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *Certificate) GetFingerprintSha256() string {
	if x != nil {
		return x.FingerprintSha256
	}
	return ""
}

func (x *Certificate) GetStatus() CertificateStatus {
	if x != nil {
		return x.Status
	}
	return CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED
}

type CertificateBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *Certificate           `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	CertPem       string                 `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	ChainPem      string                 `protobuf:"bytes,3,opt,name=chain_pem,json=chainPem,proto3" json:"chain_pem,omitempty"`
	BundlePem     string                 `protobuf:"bytes,4,opt,name=bundle_pem,json=bundlePem,proto3" json:"bundle_pem,omitempty"` // trust roots
	KeyPem        string                 `protobuf:"bytes,5,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`          // present only when the module generated the key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateBundle) Reset() {
	*x = CertificateBundle{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateBundle) ProtoMessage() {}

func (x *CertificateBundle) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateBundle.ProtoReflect.Descriptor instead.
func (*CertificateBundle) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateBundle) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *CertificateBundle) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CertificateBundle) GetChainPem() string {
	if x != nil {
		return x.ChainPem
	}
	return ""
}

func (x *CertificateBundle) GetBundlePem() string {
	if x != nil {
		return x.BundlePem
	}
	return ""
}

func (x *CertificateBundle) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CertificateId string                 `protobuf:"bytes,2,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	IncludeKey    bool                   `protobuf:"varint,3,opt,name=include_key,json=includeKey,proto3" json:"include_key,omitempty"` // include the retained private key (when lcm holds it)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DownloadRequest) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *DownloadRequest) GetIncludeKey() bool {
	if x != nil {
		return x.IncludeKey
	}
	return false
}

type IssueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IssuerId        string                 `protobuf:"bytes,2,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"` // default issuer when empty
	SpiffeId        string                 `protobuf:"bytes,3,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	CsrPem          string                 `protobuf:"bytes,4,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"` // sign this CSR; otherwise the module generates the key
	DnsSans         []string               `protobuf:"bytes,5,rep,name=dns_sans,json=dnsSans,proto3" json:"dns_sans,omitempty"`
	ValiditySeconds int64                  `protobuf:"varint,6,opt,name=validity_seconds,json=validitySeconds,proto3" json:"validity_seconds,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueRequest) Reset() {
	*x = IssueRequest{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRequest) ProtoMessage() {}

func (x *IssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRequest.ProtoReflect.Descriptor instead.
func (*IssueRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{3}
}

func (x *IssueRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IssueRequest) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *IssueRequest) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *IssueRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *IssueRequest) GetDnsSans() []string {
	if x != nil {
		return x.DnsSans
	}
	return nil
}

func (x *IssueRequest) GetValiditySeconds() int64 {
	if x != nil {
		return x.ValiditySeconds
	}
	return 0
}

func (x *IssueRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CertificateId string                 `protobuf:"bytes,2,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	CsrPem        string                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{4}
}

func (x *RenewRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RenewRequest) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *RenewRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CertificateId string                 `protobuf:"bytes,2,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeRequest) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *RevokeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"` // or spiffe_id / fingerprint
	SpiffeId      string                 `protobuf:"bytes,3,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VerifyRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *VerifyRequest) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Status        CertificateStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=lcm.v1.CertificateStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // no_certificate | revoked | expired | ok
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResponse) GetStatus() CertificateStatus {
	if x != nil {
		return x.Status
	}
	return CertificateStatus_CERTIFICATE_STATUS_UNSPECIFIED
}

func (x *VerifyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TrustBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TrustDomain   string                 `protobuf:"bytes,2,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustBundleRequest) Reset() {
	*x = TrustBundleRequest{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustBundleRequest) ProtoMessage() {}

func (x *TrustBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustBundleRequest.ProtoReflect.Descriptor instead.
func (*TrustBundleRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{9}
}

func (x *TrustBundleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TrustBundleRequest) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

type TrustBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundlePem     string                 `protobuf:"bytes,1,opt,name=bundle_pem,json=bundlePem,proto3" json:"bundle_pem,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustBundleResponse) Reset() {
	*x = TrustBundleResponse{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustBundleResponse) ProtoMessage() {}

func (x *TrustBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustBundleResponse.ProtoReflect.Descriptor instead.
func (*TrustBundleResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{10}
}

func (x *TrustBundleResponse) GetBundlePem() string {
	if x != nil {
		return x.BundlePem
	}
	return ""
}

func (x *TrustBundleResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SpiffeId        string                 `protobuf:"bytes,2,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	CsrPem          string                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	EnrollmentToken string                 `protobuf:"bytes,4,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // auth-minted; empty when enrolling with the caller identity
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{11}
}

func (x *EnrollRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnrollRequest) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // targeted; empty + all=true for everyone
	All           bool                   `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // certificate.issued | renewed | revoked
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // JSON, no key material
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{12}
}

func (x *PublishRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PublishRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *PublishRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *PublishRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{13}
}

func (x *PublishResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LastEventId   string                 `protobuf:"bytes,2,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"` // replay from here within the window
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{14}
}

func (x *WatchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WatchRequest) GetLastEventId() string {
	if x != nil {
		return x.LastEventId
	}
	return ""
}

type CertificateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // issued | renewed | revoked
	CertificateId string                 `protobuf:"bytes,3,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	SpiffeId      string                 `protobuf:"bytes,4,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateUpdate) Reset() {
	*x = CertificateUpdate{}
	mi := &file_lcm_v1_lcm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateUpdate) ProtoMessage() {}

func (x *CertificateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_lcm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateUpdate.ProtoReflect.Descriptor instead.
func (*CertificateUpdate) Descriptor() ([]byte, []int) {
	return file_lcm_v1_lcm_proto_rawDescGZIP(), []int{15}
}

func (x *CertificateUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateUpdate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CertificateUpdate) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *CertificateUpdate) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *CertificateUpdate) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

var File_lcm_v1_lcm_proto protoreflect.FileDescriptor

const file_lcm_v1_lcm_proto_rawDesc = "" +
	"\n" +
	"\x10lcm/v1/lcm.proto\x12\x06lcm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x02\n" +
	"\vCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x1b\n" +
	"\tspiffe_id\x18\x03 \x01(\tR\bspiffeId\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1b\n" +
	"\tissuer_id\x18\x05 \x01(\tR\bissuerId\x12\x12\n" +
	"\x04sans\x18\x06 \x03(\tR\x04sans\x129\n" +
	"\n" +
	"not_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12-\n" +
	"\x12fingerprint_sha256\x18\t \x01(\tR\x11fingerprintSha256\x121\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x19.lcm.v1.CertificateStatusR\x06status\"\xba\x01\n" +
	"\x11CertificateBundle\x125\n" +
	"\vcertificate\x18\x01 \x01(\v2\x13.lcm.v1.CertificateR\vcertificate\x12\x19\n" +
	"\bcert_pem\x18\x02 \x01(\tR\acertPem\x12\x1b\n" +
	"\tchain_pem\x18\x03 \x01(\tR\bchainPem\x12\x1d\n" +
	"\n" +
	"bundle_pem\x18\x04 \x01(\tR\tbundlePem\x12\x17\n" +
	"\akey_pem\x18\x05 \x01(\tR\x06keyPem\"v\n" +
	"\x0fDownloadRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0ecertificate_id\x18\x02 \x01(\tR\rcertificateId\x12\x1f\n" +
	"\vinclude_key\x18\x03 \x01(\bR\n" +
	"includeKey\"\xeb\x01\n" +
	"\fIssueRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tissuer_id\x18\x02 \x01(\tR\bissuerId\x12\x1b\n" +
	"\tspiffe_id\x18\x03 \x01(\tR\bspiffeId\x12\x17\n" +
	"\acsr_pem\x18\x04 \x01(\tR\x06csrPem\x12\x19\n" +
	"\bdns_sans\x18\x05 \x03(\tR\adnsSans\x12)\n" +
	"\x10validity_seconds\x18\x06 \x01(\x03R\x0fvaliditySeconds\x12%\n" +
	"\x0ecorrelation_id\x18\a \x01(\tR\rcorrelationId\"k\n" +
	"\fRenewRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0ecertificate_id\x18\x02 \x01(\tR\rcertificateId\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\tR\x06csrPem\"k\n" +
	"\rRevokeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0ecertificate_id\x18\x02 \x01(\tR\rcertificateId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"*\n" +
	"\x0eRevokeResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\"a\n" +
	"\rVerifyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x1b\n" +
	"\tspiffe_id\x18\x03 \x01(\tR\bspiffeId\"q\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.lcm.v1.CertificateStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"T\n" +
	"\x12TrustBundleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\ftrust_domain\x18\x02 \x01(\tR\vtrustDomain\"P\n" +
	"\x13TrustBundleResponse\x12\x1d\n" +
	"\n" +
	"bundle_pem\x18\x01 \x01(\tR\tbundlePem\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\"\x8d\x01\n" +
	"\rEnrollRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tspiffe_id\x18\x02 \x01(\tR\bspiffeId\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\tR\x06csrPem\x12)\n" +
	"\x10enrollment_token\x18\x04 \x01(\tR\x0fenrollmentToken\"\x82\x01\n" +
	"\x0ePublishRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\",\n" +
	"\x0fPublishResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"O\n" +
	"\fWatchRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\"\n" +
	"\rlast_event_id\x18\x02 \x01(\tR\vlastEventId\"\xb4\x01\n" +
	"\x11CertificateUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12%\n" +
	"\x0ecertificate_id\x18\x03 \x01(\tR\rcertificateId\x12\x1b\n" +
	"\tspiffe_id\x18\x04 \x01(\tR\bspiffeId\x127\n" +
	"\tnot_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter*\xb7\x01\n" +
	"\x11CertificateStatus\x12\"\n" +
	"\x1eCERTIFICATE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CERTIFICATE_STATUS_ACTIVE\x10\x01\x12\x1f\n" +
	"\x1bCERTIFICATE_STATUS_EXPIRING\x10\x02\x12\x1e\n" +
	"\x1aCERTIFICATE_STATUS_EXPIRED\x10\x03\x12\x1e\n" +
	"\x1aCERTIFICATE_STATUS_REVOKED\x10\x042\xb7\x02\n" +
	"\x04SVID\x128\n" +
	"\x05Issue\x12\x14.lcm.v1.IssueRequest\x1a\x19.lcm.v1.CertificateBundle\x128\n" +
	"\x05Renew\x12\x14.lcm.v1.RenewRequest\x1a\x19.lcm.v1.CertificateBundle\x127\n" +
	"\x06Revoke\x12\x15.lcm.v1.RevokeRequest\x1a\x16.lcm.v1.RevokeResponse\x127\n" +
	"\x06Verify\x12\x15.lcm.v1.VerifyRequest\x1a\x16.lcm.v1.VerifyResponse\x12I\n" +
	"\x0eGetTrustBundle\x12\x1a.lcm.v1.TrustBundleRequest\x1a\x1b.lcm.v1.TrustBundleResponse2H\n" +
	"\n" +
	"Enrollment\x12:\n" +
	"\x06Enroll\x12\x15.lcm.v1.EnrollRequest\x1a\x19.lcm.v1.CertificateBundle2D\n" +
	"\x06Events\x12:\n" +
	"\aPublish\x12\x16.lcm.v1.PublishRequest\x1a\x17.lcm.v1.PublishResponse2C\n" +
	"\x05Agent\x12:\n" +
	"\x05Watch\x12\x14.lcm.v1.WatchRequest\x1a\x19.lcm.v1.CertificateUpdate0\x012N\n" +
	"\fCertificates\x12>\n" +
	"\bDownload\x12\x17.lcm.v1.DownloadRequest\x1a\x19.lcm.v1.CertificateBundleBBZ@github.com/go-tangra/go-tangra-lcm/sdk/v4/api/proto/lcm/v1;lcmv1b\x06proto3"

var (
	file_lcm_v1_lcm_proto_rawDescOnce sync.Once
	file_lcm_v1_lcm_proto_rawDescData []byte
)

func file_lcm_v1_lcm_proto_rawDescGZIP() []byte {
	file_lcm_v1_lcm_proto_rawDescOnce.Do(func() {
		file_lcm_v1_lcm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lcm_v1_lcm_proto_rawDesc), len(file_lcm_v1_lcm_proto_rawDesc)))
	})
	return file_lcm_v1_lcm_proto_rawDescData
}

var file_lcm_v1_lcm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lcm_v1_lcm_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_lcm_v1_lcm_proto_goTypes = []any{
	(CertificateStatus)(0),        // 0: lcm.v1.CertificateStatus
	(*Certificate)(nil),           // 1: lcm.v1.Certificate
	(*CertificateBundle)(nil),     // 2: lcm.v1.CertificateBundle
	(*DownloadRequest)(nil),       // 3: lcm.v1.DownloadRequest
	(*IssueRequest)(nil),          // 4: lcm.v1.IssueRequest
	(*RenewRequest)(nil),          // 5: lcm.v1.RenewRequest
	(*RevokeRequest)(nil),         // 6: lcm.v1.RevokeRequest
	(*RevokeResponse)(nil),        // 7: lcm.v1.RevokeResponse
	(*VerifyRequest)(nil),         // 8: lcm.v1.VerifyRequest
	(*VerifyResponse)(nil),        // 9: lcm.v1.VerifyResponse
	(*TrustBundleRequest)(nil),    // 10: lcm.v1.TrustBundleRequest
	(*TrustBundleResponse)(nil),   // 11: lcm.v1.TrustBundleResponse
	(*EnrollRequest)(nil),         // 12: lcm.v1.EnrollRequest
	(*PublishRequest)(nil),        // 13: lcm.v1.PublishRequest
	(*PublishResponse)(nil),       // 14: lcm.v1.PublishResponse
	(*WatchRequest)(nil),          // 15: lcm.v1.WatchRequest
	(*CertificateUpdate)(nil),     // 16: lcm.v1.CertificateUpdate
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_lcm_v1_lcm_proto_depIdxs = []int32{
	17, // 0: lcm.v1.Certificate.not_before:type_name -> google.protobuf.Timestamp
	17, // 1: lcm.v1.Certificate.not_after:type_name -> google.protobuf.Timestamp
	0,  // 2: lcm.v1.Certificate.status:type_name -> lcm.v1.CertificateStatus
	1,  // 3: lcm.v1.CertificateBundle.certificate:type_name -> lcm.v1.Certificate
	0,  // 4: lcm.v1.VerifyResponse.status:type_name -> lcm.v1.CertificateStatus
	17, // 5: lcm.v1.CertificateUpdate.not_after:type_name -> google.protobuf.Timestamp
	4,  // 6: lcm.v1.SVID.Issue:input_type -> lcm.v1.IssueRequest
	5,  // 7: lcm.v1.SVID.Renew:input_type -> lcm.v1.RenewRequest
	6,  // 8: lcm.v1.SVID.Revoke:input_type -> lcm.v1.RevokeRequest
	8,  // 9: lcm.v1.SVID.Verify:input_type -> lcm.v1.VerifyRequest
	10, // 10: lcm.v1.SVID.GetTrustBundle:input_type -> lcm.v1.TrustBundleRequest
	12, // 11: lcm.v1.Enrollment.Enroll:input_type -> lcm.v1.EnrollRequest
	13, // 12: lcm.v1.Events.Publish:input_type -> lcm.v1.PublishRequest
	15, // 13: lcm.v1.Agent.Watch:input_type -> lcm.v1.WatchRequest
	3,  // 14: lcm.v1.Certificates.Download:input_type -> lcm.v1.DownloadRequest
	2,  // 15: lcm.v1.SVID.Issue:output_type -> lcm.v1.CertificateBundle
	2,  // 16: lcm.v1.SVID.Renew:output_type -> lcm.v1.CertificateBundle
	7,  // 17: lcm.v1.SVID.Revoke:output_type -> lcm.v1.RevokeResponse
	9,  // 18: lcm.v1.SVID.Verify:output_type -> lcm.v1.VerifyResponse
	11, // 19: lcm.v1.SVID.GetTrustBundle:output_type -> lcm.v1.TrustBundleResponse
	2,  // 20: lcm.v1.Enrollment.Enroll:output_type -> lcm.v1.CertificateBundle
	14, // 21: lcm.v1.Events.Publish:output_type -> lcm.v1.PublishResponse
	16, // 22: lcm.v1.Agent.Watch:output_type -> lcm.v1.CertificateUpdate
	2,  // 23: lcm.v1.Certificates.Download:output_type -> lcm.v1.CertificateBundle
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_lcm_v1_lcm_proto_init() }
func file_lcm_v1_lcm_proto_init() {
	if File_lcm_v1_lcm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lcm_v1_lcm_proto_rawDesc), len(file_lcm_v1_lcm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_lcm_v1_lcm_proto_goTypes,
		DependencyIndexes: file_lcm_v1_lcm_proto_depIdxs,
		EnumInfos:         file_lcm_v1_lcm_proto_enumTypes,
		MessageInfos:      file_lcm_v1_lcm_proto_msgTypes,
	}.Build()
	File_lcm_v1_lcm_proto = out.File
	file_lcm_v1_lcm_proto_goTypes = nil
	file_lcm_v1_lcm_proto_depIdxs = nil
}
