// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-lcm/internal/data/ent/clientinstalledcertificate"
)

// ClientInstalledCertificateCreate is the builder for creating a ClientInstalledCertificate entity.
type ClientInstalledCertificateCreate struct {
	config
	mutation *ClientInstalledCertificateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *ClientInstalledCertificateCreate) SetCreateTime(v time.Time) *ClientInstalledCertificateCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ClientInstalledCertificateCreate) SetNillableCreateTime(v *time.Time) *ClientInstalledCertificateCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ClientInstalledCertificateCreate) SetUpdateTime(v time.Time) *ClientInstalledCertificateCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ClientInstalledCertificateCreate) SetNillableUpdateTime(v *time.Time) *ClientInstalledCertificateCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *ClientInstalledCertificateCreate) SetDeleteTime(v time.Time) *ClientInstalledCertificateCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *ClientInstalledCertificateCreate) SetNillableDeleteTime(v *time.Time) *ClientInstalledCertificateCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ClientInstalledCertificateCreate) SetTenantID(v uint32) *ClientInstalledCertificateCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ClientInstalledCertificateCreate) SetNillableTenantID(v *uint32) *ClientInstalledCertificateCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *ClientInstalledCertificateCreate) SetClientID(v string) *ClientInstalledCertificateCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ClientInstalledCertificateCreate) SetName(v string) *ClientInstalledCertificateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSerialNumber sets the "serial_number" field.
func (_c *ClientInstalledCertificateCreate) SetSerialNumber(v string) *ClientInstalledCertificateCreate {
	_c.mutation.SetSerialNumber(v)
	return _c
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_c *ClientInstalledCertificateCreate) SetNillableSerialNumber(v *string) *ClientInstalledCertificateCreate {
	if v != nil {
		_c.SetSerialNumber(*v)
	}
	return _c
}

// SetFingerprintSha256 sets the "fingerprint_sha256" field.
func (_c *ClientInstalledCertificateCreate) SetFingerprintSha256(v string) *ClientInstalledCertificateCreate {
	_c.mutation.SetFingerprintSha256(v)
	return _c
}

// SetNillableFingerprintSha256 sets the "fingerprint_sha256" field if the given value is not nil.
func (_c *ClientInstalledCertificateCreate) SetNillableFingerprintSha256(v *string) *ClientInstalledCertificateCreate {
	if v != nil {
		_c.SetFingerprintSha256(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ClientInstalledCertificateCreate) SetStatus(v clientinstalledcertificate.Status) *ClientInstalledCertificateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ClientInstalledCertificateCreate) SetNillableStatus(v *clientinstalledcertificate.Status) *ClientInstalledCertificateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *ClientInstalledCertificateCreate) SetMessage(v string) *ClientInstalledCertificateCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *ClientInstalledCertificateCreate) SetNillableMessage(v *string) *ClientInstalledCertificateCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetInstalledAt sets the "installed_at" field.
func (_c *ClientInstalledCertificateCreate) SetInstalledAt(v time.Time) *ClientInstalledCertificateCreate {
	_c.mutation.SetInstalledAt(v)
	return _c
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (_c *ClientInstalledCertificateCreate) SetNillableInstalledAt(v *time.Time) *ClientInstalledCertificateCreate {
	if v != nil {
		_c.SetInstalledAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ClientInstalledCertificateCreate) SetID(v uint32) *ClientInstalledCertificateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ClientInstalledCertificateMutation object of the builder.
func (_c *ClientInstalledCertificateCreate) Mutation() *ClientInstalledCertificateMutation {
	return _c.mutation
}

// Save creates the ClientInstalledCertificate in the database.
func (_c *ClientInstalledCertificateCreate) Save(ctx context.Context) (*ClientInstalledCertificate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClientInstalledCertificateCreate) SaveX(ctx context.Context) *ClientInstalledCertificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientInstalledCertificateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientInstalledCertificateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClientInstalledCertificateCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := clientinstalledcertificate.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := clientinstalledcertificate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClientInstalledCertificateCreate) check() error {
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "ClientInstalledCertificate.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := clientinstalledcertificate.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ClientInstalledCertificate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := clientinstalledcertificate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ClientInstalledCertificate.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := clientinstalledcertificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := clientinstalledcertificate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ClientInstalledCertificateCreate) sqlSave(ctx context.Context) (*ClientInstalledCertificate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClientInstalledCertificateCreate) createSpec() (*ClientInstalledCertificate, *sqlgraph.CreateSpec) {
	var (
		_node = &ClientInstalledCertificate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clientinstalledcertificate.Table, sqlgraph.NewFieldSpec(clientinstalledcertificate.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(clientinstalledcertificate.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(clientinstalledcertificate.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(clientinstalledcertificate.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(clientinstalledcertificate.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(clientinstalledcertificate.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(clientinstalledcertificate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SerialNumber(); ok {
		_spec.SetField(clientinstalledcertificate.FieldSerialNumber, field.TypeString, value)
		_node.SerialNumber = value
	}
	if value, ok := _c.mutation.FingerprintSha256(); ok {
		_spec.SetField(clientinstalledcertificate.FieldFingerprintSha256, field.TypeString, value)
		_node.FingerprintSha256 = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(clientinstalledcertificate.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(clientinstalledcertificate.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.InstalledAt(); ok {
		_spec.SetField(clientinstalledcertificate.FieldInstalledAt, field.TypeTime, value)
		_node.InstalledAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ClientInstalledCertificate.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ClientInstalledCertificateUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *ClientInstalledCertificateCreate) OnConflict(opts ...sql.ConflictOption) *ClientInstalledCertificateUpsertOne {
	_c.conflict = opts
	return &ClientInstalledCertificateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ClientInstalledCertificate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ClientInstalledCertificateCreate) OnConflictColumns(columns ...string) *ClientInstalledCertificateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ClientInstalledCertificateUpsertOne{
		create: _c,
	}
}

type (
	// ClientInstalledCertificateUpsertOne is the builder for "upsert"-ing
	//  one ClientInstalledCertificate node.
	ClientInstalledCertificateUpsertOne struct {
		create *ClientInstalledCertificateCreate
	}

	// ClientInstalledCertificateUpsert is the "OnConflict" setter.
	ClientInstalledCertificateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *ClientInstalledCertificateUpsert) SetUpdateTime(v time.Time) *ClientInstalledCertificateUpsert {
	u.Set(clientinstalledcertificate.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsert) UpdateUpdateTime() *ClientInstalledCertificateUpsert {
	u.SetExcluded(clientinstalledcertificate.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ClientInstalledCertificateUpsert) ClearUpdateTime() *ClientInstalledCertificateUpsert {
	u.SetNull(clientinstalledcertificate.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *ClientInstalledCertificateUpsert) SetDeleteTime(v time.Time) *ClientInstalledCertificateUpsert {
	u.Set(clientinstalledcertificate.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsert) UpdateDeleteTime() *ClientInstalledCertificateUpsert {
	u.SetExcluded(clientinstalledcertificate.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ClientInstalledCertificateUpsert) ClearDeleteTime() *ClientInstalledCertificateUpsert {
	u.SetNull(clientinstalledcertificate.FieldDeleteTime)
	return u
}

// SetClientID sets the "client_id" field.
func (u *ClientInstalledCertificateUpsert) SetClientID(v string) *ClientInstalledCertificateUpsert {
	u.Set(clientinstalledcertificate.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsert) UpdateClientID() *ClientInstalledCertificateUpsert {
	u.SetExcluded(clientinstalledcertificate.FieldClientID)
	return u
}

// SetName sets the "name" field.
func (u *ClientInstalledCertificateUpsert) SetName(v string) *ClientInstalledCertificateUpsert {
	u.Set(clientinstalledcertificate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsert) UpdateName() *ClientInstalledCertificateUpsert {
	u.SetExcluded(clientinstalledcertificate.FieldName)
	return u
}

// SetSerialNumber sets the "serial_number" field.
func (u *ClientInstalledCertificateUpsert) SetSerialNumber(v string) *ClientInstalledCertificateUpsert {
	u.Set(clientinstalledcertificate.FieldSerialNumber, v)
	return u
}

// UpdateSerialNumber sets the "serial_number" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsert) UpdateSerialNumber() *ClientInstalledCertificateUpsert {
	u.SetExcluded(clientinstalledcertificate.FieldSerialNumber)
	return u
}

// ClearSerialNumber clears the value of the "serial_number" field.
func (u *ClientInstalledCertificateUpsert) ClearSerialNumber() *ClientInstalledCertificateUpsert {
	u.SetNull(clientinstalledcertificate.FieldSerialNumber)
	return u
}

// SetFingerprintSha256 sets the "fingerprint_sha256" field.
func (u *ClientInstalledCertificateUpsert) SetFingerprintSha256(v string) *ClientInstalledCertificateUpsert {
	u.Set(clientinstalledcertificate.FieldFingerprintSha256, v)
	return u
}

// UpdateFingerprintSha256 sets the "fingerprint_sha256" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsert) UpdateFingerprintSha256() *ClientInstalledCertificateUpsert {
	u.SetExcluded(clientinstalledcertificate.FieldFingerprintSha256)
	return u
}

// ClearFingerprintSha256 clears the value of the "fingerprint_sha256" field.
func (u *ClientInstalledCertificateUpsert) ClearFingerprintSha256() *ClientInstalledCertificateUpsert {
	u.SetNull(clientinstalledcertificate.FieldFingerprintSha256)
	return u
}

// SetStatus sets the "status" field.
func (u *ClientInstalledCertificateUpsert) SetStatus(v clientinstalledcertificate.Status) *ClientInstalledCertificateUpsert {
	u.Set(clientinstalledcertificate.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsert) UpdateStatus() *ClientInstalledCertificateUpsert {
	u.SetExcluded(clientinstalledcertificate.FieldStatus)
	return u
}

// SetMessage sets the "message" field.
func (u *ClientInstalledCertificateUpsert) SetMessage(v string) *ClientInstalledCertificateUpsert {
	u.Set(clientinstalledcertificate.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsert) UpdateMessage() *ClientInstalledCertificateUpsert {
	u.SetExcluded(clientinstalledcertificate.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *ClientInstalledCertificateUpsert) ClearMessage() *ClientInstalledCertificateUpsert {
	u.SetNull(clientinstalledcertificate.FieldMessage)
	return u
}

// SetInstalledAt sets the "installed_at" field.
func (u *ClientInstalledCertificateUpsert) SetInstalledAt(v time.Time) *ClientInstalledCertificateUpsert {
	u.Set(clientinstalledcertificate.FieldInstalledAt, v)
	return u
}

// UpdateInstalledAt sets the "installed_at" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsert) UpdateInstalledAt() *ClientInstalledCertificateUpsert {
	u.SetExcluded(clientinstalledcertificate.FieldInstalledAt)
	return u
}

// ClearInstalledAt clears the value of the "installed_at" field.
func (u *ClientInstalledCertificateUpsert) ClearInstalledAt() *ClientInstalledCertificateUpsert {
	u.SetNull(clientinstalledcertificate.FieldInstalledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ClientInstalledCertificate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(clientinstalledcertificate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ClientInstalledCertificateUpsertOne) UpdateNewValues() *ClientInstalledCertificateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(clientinstalledcertificate.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(clientinstalledcertificate.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(clientinstalledcertificate.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ClientInstalledCertificate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ClientInstalledCertificateUpsertOne) Ignore() *ClientInstalledCertificateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ClientInstalledCertificateUpsertOne) DoNothing() *ClientInstalledCertificateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ClientInstalledCertificateCreate.OnConflict
// documentation for more info.
func (u *ClientInstalledCertificateUpsertOne) Update(set func(*ClientInstalledCertificateUpsert)) *ClientInstalledCertificateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ClientInstalledCertificateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ClientInstalledCertificateUpsertOne) SetUpdateTime(v time.Time) *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertOne) UpdateUpdateTime() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ClientInstalledCertificateUpsertOne) ClearUpdateTime() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ClientInstalledCertificateUpsertOne) SetDeleteTime(v time.Time) *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertOne) UpdateDeleteTime() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ClientInstalledCertificateUpsertOne) ClearDeleteTime() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetClientID sets the "client_id" field.
func (u *ClientInstalledCertificateUpsertOne) SetClientID(v string) *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertOne) UpdateClientID() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateClientID()
	})
}

// SetName sets the "name" field.
func (u *ClientInstalledCertificateUpsertOne) SetName(v string) *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertOne) UpdateName() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateName()
	})
}

// SetSerialNumber sets the "serial_number" field.
func (u *ClientInstalledCertificateUpsertOne) SetSerialNumber(v string) *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetSerialNumber(v)
	})
}

// UpdateSerialNumber sets the "serial_number" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertOne) UpdateSerialNumber() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateSerialNumber()
	})
}

// ClearSerialNumber clears the value of the "serial_number" field.
func (u *ClientInstalledCertificateUpsertOne) ClearSerialNumber() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearSerialNumber()
	})
}

// SetFingerprintSha256 sets the "fingerprint_sha256" field.
func (u *ClientInstalledCertificateUpsertOne) SetFingerprintSha256(v string) *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetFingerprintSha256(v)
	})
}

// UpdateFingerprintSha256 sets the "fingerprint_sha256" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertOne) UpdateFingerprintSha256() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateFingerprintSha256()
	})
}

// ClearFingerprintSha256 clears the value of the "fingerprint_sha256" field.
func (u *ClientInstalledCertificateUpsertOne) ClearFingerprintSha256() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearFingerprintSha256()
	})
}

// SetStatus sets the "status" field.
func (u *ClientInstalledCertificateUpsertOne) SetStatus(v clientinstalledcertificate.Status) *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertOne) UpdateStatus() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *ClientInstalledCertificateUpsertOne) SetMessage(v string) *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertOne) UpdateMessage() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *ClientInstalledCertificateUpsertOne) ClearMessage() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearMessage()
	})
}

// SetInstalledAt sets the "installed_at" field.
func (u *ClientInstalledCertificateUpsertOne) SetInstalledAt(v time.Time) *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetInstalledAt(v)
	})
}

// UpdateInstalledAt sets the "installed_at" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertOne) UpdateInstalledAt() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateInstalledAt()
	})
}

// ClearInstalledAt clears the value of the "installed_at" field.
func (u *ClientInstalledCertificateUpsertOne) ClearInstalledAt() *ClientInstalledCertificateUpsertOne {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearInstalledAt()
	})
}

// Exec executes the query.
func (u *ClientInstalledCertificateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ClientInstalledCertificateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ClientInstalledCertificateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ClientInstalledCertificateUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ClientInstalledCertificateUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ClientInstalledCertificateCreateBulk is the builder for creating many ClientInstalledCertificate entities in bulk.
type ClientInstalledCertificateCreateBulk struct {
	config
	err      error
	builders []*ClientInstalledCertificateCreate
	conflict []sql.ConflictOption
}

// Save creates the ClientInstalledCertificate entities in the database.
func (_c *ClientInstalledCertificateCreateBulk) Save(ctx context.Context) ([]*ClientInstalledCertificate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ClientInstalledCertificate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientInstalledCertificateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClientInstalledCertificateCreateBulk) SaveX(ctx context.Context) []*ClientInstalledCertificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientInstalledCertificateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientInstalledCertificateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ClientInstalledCertificate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ClientInstalledCertificateUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *ClientInstalledCertificateCreateBulk) OnConflict(opts ...sql.ConflictOption) *ClientInstalledCertificateUpsertBulk {
	_c.conflict = opts
	return &ClientInstalledCertificateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ClientInstalledCertificate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ClientInstalledCertificateCreateBulk) OnConflictColumns(columns ...string) *ClientInstalledCertificateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ClientInstalledCertificateUpsertBulk{
		create: _c,
	}
}

// ClientInstalledCertificateUpsertBulk is the builder for "upsert"-ing
// a bulk of ClientInstalledCertificate nodes.
type ClientInstalledCertificateUpsertBulk struct {
	create *ClientInstalledCertificateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ClientInstalledCertificate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(clientinstalledcertificate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ClientInstalledCertificateUpsertBulk) UpdateNewValues() *ClientInstalledCertificateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(clientinstalledcertificate.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(clientinstalledcertificate.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(clientinstalledcertificate.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ClientInstalledCertificate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ClientInstalledCertificateUpsertBulk) Ignore() *ClientInstalledCertificateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ClientInstalledCertificateUpsertBulk) DoNothing() *ClientInstalledCertificateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ClientInstalledCertificateCreateBulk.OnConflict
// documentation for more info.
func (u *ClientInstalledCertificateUpsertBulk) Update(set func(*ClientInstalledCertificateUpsert)) *ClientInstalledCertificateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ClientInstalledCertificateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ClientInstalledCertificateUpsertBulk) SetUpdateTime(v time.Time) *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertBulk) UpdateUpdateTime() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ClientInstalledCertificateUpsertBulk) ClearUpdateTime() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ClientInstalledCertificateUpsertBulk) SetDeleteTime(v time.Time) *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertBulk) UpdateDeleteTime() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ClientInstalledCertificateUpsertBulk) ClearDeleteTime() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetClientID sets the "client_id" field.
func (u *ClientInstalledCertificateUpsertBulk) SetClientID(v string) *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertBulk) UpdateClientID() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateClientID()
	})
}

// SetName sets the "name" field.
func (u *ClientInstalledCertificateUpsertBulk) SetName(v string) *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertBulk) UpdateName() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateName()
	})
}

// SetSerialNumber sets the "serial_number" field.
func (u *ClientInstalledCertificateUpsertBulk) SetSerialNumber(v string) *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetSerialNumber(v)
	})
}

// UpdateSerialNumber sets the "serial_number" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertBulk) UpdateSerialNumber() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateSerialNumber()
	})
}

// ClearSerialNumber clears the value of the "serial_number" field.
func (u *ClientInstalledCertificateUpsertBulk) ClearSerialNumber() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearSerialNumber()
	})
}

// SetFingerprintSha256 sets the "fingerprint_sha256" field.
func (u *ClientInstalledCertificateUpsertBulk) SetFingerprintSha256(v string) *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetFingerprintSha256(v)
	})
}

// UpdateFingerprintSha256 sets the "fingerprint_sha256" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertBulk) UpdateFingerprintSha256() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateFingerprintSha256()
	})
}

// ClearFingerprintSha256 clears the value of the "fingerprint_sha256" field.
func (u *ClientInstalledCertificateUpsertBulk) ClearFingerprintSha256() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearFingerprintSha256()
	})
}

// SetStatus sets the "status" field.
func (u *ClientInstalledCertificateUpsertBulk) SetStatus(v clientinstalledcertificate.Status) *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertBulk) UpdateStatus() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *ClientInstalledCertificateUpsertBulk) SetMessage(v string) *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertBulk) UpdateMessage() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *ClientInstalledCertificateUpsertBulk) ClearMessage() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearMessage()
	})
}

// SetInstalledAt sets the "installed_at" field.
func (u *ClientInstalledCertificateUpsertBulk) SetInstalledAt(v time.Time) *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.SetInstalledAt(v)
	})
}

// UpdateInstalledAt sets the "installed_at" field to the value that was provided on create.
func (u *ClientInstalledCertificateUpsertBulk) UpdateInstalledAt() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.UpdateInstalledAt()
	})
}

// ClearInstalledAt clears the value of the "installed_at" field.
func (u *ClientInstalledCertificateUpsertBulk) ClearInstalledAt() *ClientInstalledCertificateUpsertBulk {
	return u.Update(func(s *ClientInstalledCertificateUpsert) {
		s.ClearInstalledAt()
	})
}

// Exec executes the query.
func (u *ClientInstalledCertificateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ClientInstalledCertificateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ClientInstalledCertificateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ClientInstalledCertificateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
