// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-lcm/internal/data/ent/clientinstalledcertificate"
)

// ClientInstalledCertificate is the model entity for the ClientInstalledCertificate schema.
type ClientInstalledCertificate struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Logical client identifier (matches LcmClient.client_id)
	ClientID string `json:"client_id,omitempty"`
	// Certificate name on the agent (e.g. CN or pusher override)
	Name string `json:"name,omitempty"`
	// Serial number of the installed certificate
	SerialNumber string `json:"serial_number,omitempty"`
	// SHA256 fingerprint of the installed certificate
	FingerprintSha256 string `json:"fingerprint_sha256,omitempty"`
	// Last reported status from the agent
	Status clientinstalledcertificate.Status `json:"status,omitempty"`
	// Free-form message from the agent (error text on failures)
	Message string `json:"message,omitempty"`
	// When the agent applied this certificate
	InstalledAt  *time.Time `json:"installed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClientInstalledCertificate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clientinstalledcertificate.FieldID, clientinstalledcertificate.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case clientinstalledcertificate.FieldClientID, clientinstalledcertificate.FieldName, clientinstalledcertificate.FieldSerialNumber, clientinstalledcertificate.FieldFingerprintSha256, clientinstalledcertificate.FieldStatus, clientinstalledcertificate.FieldMessage:
			values[i] = new(sql.NullString)
		case clientinstalledcertificate.FieldCreateTime, clientinstalledcertificate.FieldUpdateTime, clientinstalledcertificate.FieldDeleteTime, clientinstalledcertificate.FieldInstalledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClientInstalledCertificate fields.
func (_m *ClientInstalledCertificate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clientinstalledcertificate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case clientinstalledcertificate.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case clientinstalledcertificate.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case clientinstalledcertificate.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case clientinstalledcertificate.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case clientinstalledcertificate.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case clientinstalledcertificate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case clientinstalledcertificate.FieldSerialNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field serial_number", values[i])
			} else if value.Valid {
				_m.SerialNumber = value.String
			}
		case clientinstalledcertificate.FieldFingerprintSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint_sha256", values[i])
			} else if value.Valid {
				_m.FingerprintSha256 = value.String
			}
		case clientinstalledcertificate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = clientinstalledcertificate.Status(value.String)
			}
		case clientinstalledcertificate.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case clientinstalledcertificate.FieldInstalledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field installed_at", values[i])
			} else if value.Valid {
				_m.InstalledAt = new(time.Time)
				*_m.InstalledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ClientInstalledCertificate.
// This includes values selected through modifiers, order, etc.
func (_m *ClientInstalledCertificate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ClientInstalledCertificate.
// Note that you need to call ClientInstalledCertificate.Unwrap() before calling this method if this ClientInstalledCertificate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ClientInstalledCertificate) Update() *ClientInstalledCertificateUpdateOne {
	return NewClientInstalledCertificateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ClientInstalledCertificate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ClientInstalledCertificate) Unwrap() *ClientInstalledCertificate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClientInstalledCertificate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ClientInstalledCertificate) String() string {
	var builder strings.Builder
	builder.WriteString("ClientInstalledCertificate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("serial_number=")
	builder.WriteString(_m.SerialNumber)
	builder.WriteString(", ")
	builder.WriteString("fingerprint_sha256=")
	builder.WriteString(_m.FingerprintSha256)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	if v := _m.InstalledAt; v != nil {
		builder.WriteString("installed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ClientInstalledCertificates is a parsable slice of ClientInstalledCertificate.
type ClientInstalledCertificates []*ClientInstalledCertificate
