// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-lcm/internal/data/ent/clientinstalledcertificate"
	"github.com/go-tangra/go-tangra-lcm/internal/data/ent/predicate"
)

// ClientInstalledCertificateUpdate is the builder for updating ClientInstalledCertificate entities.
type ClientInstalledCertificateUpdate struct {
	config
	hooks     []Hook
	mutation  *ClientInstalledCertificateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ClientInstalledCertificateUpdate builder.
func (_u *ClientInstalledCertificateUpdate) Where(ps ...predicate.ClientInstalledCertificate) *ClientInstalledCertificateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ClientInstalledCertificateUpdate) SetUpdateTime(v time.Time) *ClientInstalledCertificateUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdate) SetNillableUpdateTime(v *time.Time) *ClientInstalledCertificateUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ClientInstalledCertificateUpdate) ClearUpdateTime() *ClientInstalledCertificateUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ClientInstalledCertificateUpdate) SetDeleteTime(v time.Time) *ClientInstalledCertificateUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdate) SetNillableDeleteTime(v *time.Time) *ClientInstalledCertificateUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ClientInstalledCertificateUpdate) ClearDeleteTime() *ClientInstalledCertificateUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ClientInstalledCertificateUpdate) SetClientID(v string) *ClientInstalledCertificateUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdate) SetNillableClientID(v *string) *ClientInstalledCertificateUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ClientInstalledCertificateUpdate) SetName(v string) *ClientInstalledCertificateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdate) SetNillableName(v *string) *ClientInstalledCertificateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSerialNumber sets the "serial_number" field.
func (_u *ClientInstalledCertificateUpdate) SetSerialNumber(v string) *ClientInstalledCertificateUpdate {
	_u.mutation.SetSerialNumber(v)
	return _u
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdate) SetNillableSerialNumber(v *string) *ClientInstalledCertificateUpdate {
	if v != nil {
		_u.SetSerialNumber(*v)
	}
	return _u
}

// ClearSerialNumber clears the value of the "serial_number" field.
func (_u *ClientInstalledCertificateUpdate) ClearSerialNumber() *ClientInstalledCertificateUpdate {
	_u.mutation.ClearSerialNumber()
	return _u
}

// SetFingerprintSha256 sets the "fingerprint_sha256" field.
func (_u *ClientInstalledCertificateUpdate) SetFingerprintSha256(v string) *ClientInstalledCertificateUpdate {
	_u.mutation.SetFingerprintSha256(v)
	return _u
}

// SetNillableFingerprintSha256 sets the "fingerprint_sha256" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdate) SetNillableFingerprintSha256(v *string) *ClientInstalledCertificateUpdate {
	if v != nil {
		_u.SetFingerprintSha256(*v)
	}
	return _u
}

// ClearFingerprintSha256 clears the value of the "fingerprint_sha256" field.
func (_u *ClientInstalledCertificateUpdate) ClearFingerprintSha256() *ClientInstalledCertificateUpdate {
	_u.mutation.ClearFingerprintSha256()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ClientInstalledCertificateUpdate) SetStatus(v clientinstalledcertificate.Status) *ClientInstalledCertificateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdate) SetNillableStatus(v *clientinstalledcertificate.Status) *ClientInstalledCertificateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ClientInstalledCertificateUpdate) SetMessage(v string) *ClientInstalledCertificateUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdate) SetNillableMessage(v *string) *ClientInstalledCertificateUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *ClientInstalledCertificateUpdate) ClearMessage() *ClientInstalledCertificateUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetInstalledAt sets the "installed_at" field.
func (_u *ClientInstalledCertificateUpdate) SetInstalledAt(v time.Time) *ClientInstalledCertificateUpdate {
	_u.mutation.SetInstalledAt(v)
	return _u
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdate) SetNillableInstalledAt(v *time.Time) *ClientInstalledCertificateUpdate {
	if v != nil {
		_u.SetInstalledAt(*v)
	}
	return _u
}

// ClearInstalledAt clears the value of the "installed_at" field.
func (_u *ClientInstalledCertificateUpdate) ClearInstalledAt() *ClientInstalledCertificateUpdate {
	_u.mutation.ClearInstalledAt()
	return _u
}

// Mutation returns the ClientInstalledCertificateMutation object of the builder.
func (_u *ClientInstalledCertificateUpdate) Mutation() *ClientInstalledCertificateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClientInstalledCertificateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientInstalledCertificateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClientInstalledCertificateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientInstalledCertificateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientInstalledCertificateUpdate) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := clientinstalledcertificate.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := clientinstalledcertificate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := clientinstalledcertificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ClientInstalledCertificateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ClientInstalledCertificateUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ClientInstalledCertificateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientinstalledcertificate.Table, clientinstalledcertificate.Columns, sqlgraph.NewFieldSpec(clientinstalledcertificate.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(clientinstalledcertificate.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(clientinstalledcertificate.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(clientinstalledcertificate.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(clientinstalledcertificate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SerialNumber(); ok {
		_spec.SetField(clientinstalledcertificate.FieldSerialNumber, field.TypeString, value)
	}
	if _u.mutation.SerialNumberCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldSerialNumber, field.TypeString)
	}
	if value, ok := _u.mutation.FingerprintSha256(); ok {
		_spec.SetField(clientinstalledcertificate.FieldFingerprintSha256, field.TypeString, value)
	}
	if _u.mutation.FingerprintSha256Cleared() {
		_spec.ClearField(clientinstalledcertificate.FieldFingerprintSha256, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(clientinstalledcertificate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(clientinstalledcertificate.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.InstalledAt(); ok {
		_spec.SetField(clientinstalledcertificate.FieldInstalledAt, field.TypeTime, value)
	}
	if _u.mutation.InstalledAtCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldInstalledAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientinstalledcertificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClientInstalledCertificateUpdateOne is the builder for updating a single ClientInstalledCertificate entity.
type ClientInstalledCertificateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ClientInstalledCertificateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *ClientInstalledCertificateUpdateOne) SetUpdateTime(v time.Time) *ClientInstalledCertificateUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdateOne) SetNillableUpdateTime(v *time.Time) *ClientInstalledCertificateUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ClientInstalledCertificateUpdateOne) ClearUpdateTime() *ClientInstalledCertificateUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ClientInstalledCertificateUpdateOne) SetDeleteTime(v time.Time) *ClientInstalledCertificateUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdateOne) SetNillableDeleteTime(v *time.Time) *ClientInstalledCertificateUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ClientInstalledCertificateUpdateOne) ClearDeleteTime() *ClientInstalledCertificateUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ClientInstalledCertificateUpdateOne) SetClientID(v string) *ClientInstalledCertificateUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdateOne) SetNillableClientID(v *string) *ClientInstalledCertificateUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ClientInstalledCertificateUpdateOne) SetName(v string) *ClientInstalledCertificateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdateOne) SetNillableName(v *string) *ClientInstalledCertificateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSerialNumber sets the "serial_number" field.
func (_u *ClientInstalledCertificateUpdateOne) SetSerialNumber(v string) *ClientInstalledCertificateUpdateOne {
	_u.mutation.SetSerialNumber(v)
	return _u
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdateOne) SetNillableSerialNumber(v *string) *ClientInstalledCertificateUpdateOne {
	if v != nil {
		_u.SetSerialNumber(*v)
	}
	return _u
}

// ClearSerialNumber clears the value of the "serial_number" field.
func (_u *ClientInstalledCertificateUpdateOne) ClearSerialNumber() *ClientInstalledCertificateUpdateOne {
	_u.mutation.ClearSerialNumber()
	return _u
}

// SetFingerprintSha256 sets the "fingerprint_sha256" field.
func (_u *ClientInstalledCertificateUpdateOne) SetFingerprintSha256(v string) *ClientInstalledCertificateUpdateOne {
	_u.mutation.SetFingerprintSha256(v)
	return _u
}

// SetNillableFingerprintSha256 sets the "fingerprint_sha256" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdateOne) SetNillableFingerprintSha256(v *string) *ClientInstalledCertificateUpdateOne {
	if v != nil {
		_u.SetFingerprintSha256(*v)
	}
	return _u
}

// ClearFingerprintSha256 clears the value of the "fingerprint_sha256" field.
func (_u *ClientInstalledCertificateUpdateOne) ClearFingerprintSha256() *ClientInstalledCertificateUpdateOne {
	_u.mutation.ClearFingerprintSha256()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ClientInstalledCertificateUpdateOne) SetStatus(v clientinstalledcertificate.Status) *ClientInstalledCertificateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdateOne) SetNillableStatus(v *clientinstalledcertificate.Status) *ClientInstalledCertificateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ClientInstalledCertificateUpdateOne) SetMessage(v string) *ClientInstalledCertificateUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdateOne) SetNillableMessage(v *string) *ClientInstalledCertificateUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *ClientInstalledCertificateUpdateOne) ClearMessage() *ClientInstalledCertificateUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetInstalledAt sets the "installed_at" field.
func (_u *ClientInstalledCertificateUpdateOne) SetInstalledAt(v time.Time) *ClientInstalledCertificateUpdateOne {
	_u.mutation.SetInstalledAt(v)
	return _u
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (_u *ClientInstalledCertificateUpdateOne) SetNillableInstalledAt(v *time.Time) *ClientInstalledCertificateUpdateOne {
	if v != nil {
		_u.SetInstalledAt(*v)
	}
	return _u
}

// ClearInstalledAt clears the value of the "installed_at" field.
func (_u *ClientInstalledCertificateUpdateOne) ClearInstalledAt() *ClientInstalledCertificateUpdateOne {
	_u.mutation.ClearInstalledAt()
	return _u
}

// Mutation returns the ClientInstalledCertificateMutation object of the builder.
func (_u *ClientInstalledCertificateUpdateOne) Mutation() *ClientInstalledCertificateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ClientInstalledCertificateUpdate builder.
func (_u *ClientInstalledCertificateUpdateOne) Where(ps ...predicate.ClientInstalledCertificate) *ClientInstalledCertificateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClientInstalledCertificateUpdateOne) Select(field string, fields ...string) *ClientInstalledCertificateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ClientInstalledCertificate entity.
func (_u *ClientInstalledCertificateUpdateOne) Save(ctx context.Context) (*ClientInstalledCertificate, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientInstalledCertificateUpdateOne) SaveX(ctx context.Context) *ClientInstalledCertificate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClientInstalledCertificateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientInstalledCertificateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientInstalledCertificateUpdateOne) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := clientinstalledcertificate.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := clientinstalledcertificate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := clientinstalledcertificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ClientInstalledCertificate.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ClientInstalledCertificateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ClientInstalledCertificateUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ClientInstalledCertificateUpdateOne) sqlSave(ctx context.Context) (_node *ClientInstalledCertificate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientinstalledcertificate.Table, clientinstalledcertificate.Columns, sqlgraph.NewFieldSpec(clientinstalledcertificate.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClientInstalledCertificate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clientinstalledcertificate.FieldID)
		for _, f := range fields {
			if !clientinstalledcertificate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clientinstalledcertificate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(clientinstalledcertificate.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(clientinstalledcertificate.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(clientinstalledcertificate.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(clientinstalledcertificate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SerialNumber(); ok {
		_spec.SetField(clientinstalledcertificate.FieldSerialNumber, field.TypeString, value)
	}
	if _u.mutation.SerialNumberCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldSerialNumber, field.TypeString)
	}
	if value, ok := _u.mutation.FingerprintSha256(); ok {
		_spec.SetField(clientinstalledcertificate.FieldFingerprintSha256, field.TypeString, value)
	}
	if _u.mutation.FingerprintSha256Cleared() {
		_spec.ClearField(clientinstalledcertificate.FieldFingerprintSha256, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(clientinstalledcertificate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(clientinstalledcertificate.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.InstalledAt(); ok {
		_spec.SetField(clientinstalledcertificate.FieldInstalledAt, field.TypeTime, value)
	}
	if _u.mutation.InstalledAtCleared() {
		_spec.ClearField(clientinstalledcertificate.FieldInstalledAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ClientInstalledCertificate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientinstalledcertificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
