// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-lcm/internal/data/ent/clientinstalledcertificate"
	"github.com/go-tangra/go-tangra-lcm/internal/data/ent/predicate"
)

// ClientInstalledCertificateDelete is the builder for deleting a ClientInstalledCertificate entity.
type ClientInstalledCertificateDelete struct {
	config
	hooks    []Hook
	mutation *ClientInstalledCertificateMutation
}

// Where appends a list predicates to the ClientInstalledCertificateDelete builder.
func (_d *ClientInstalledCertificateDelete) Where(ps ...predicate.ClientInstalledCertificate) *ClientInstalledCertificateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ClientInstalledCertificateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClientInstalledCertificateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ClientInstalledCertificateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(clientinstalledcertificate.Table, sqlgraph.NewFieldSpec(clientinstalledcertificate.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ClientInstalledCertificateDeleteOne is the builder for deleting a single ClientInstalledCertificate entity.
type ClientInstalledCertificateDeleteOne struct {
	_d *ClientInstalledCertificateDelete
}

// Where appends a list predicates to the ClientInstalledCertificateDelete builder.
func (_d *ClientInstalledCertificateDeleteOne) Where(ps ...predicate.ClientInstalledCertificate) *ClientInstalledCertificateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ClientInstalledCertificateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clientinstalledcertificate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClientInstalledCertificateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
