// Code generated by ent, DO NOT EDIT.

package clientinstalledcertificate

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the clientinstalledcertificate type in the database.
	Label = "client_installed_certificate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSerialNumber holds the string denoting the serial_number field in the database.
	FieldSerialNumber = "serial_number"
	// FieldFingerprintSha256 holds the string denoting the fingerprint_sha256 field in the database.
	FieldFingerprintSha256 = "fingerprint_sha256"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldInstalledAt holds the string denoting the installed_at field in the database.
	FieldInstalledAt = "installed_at"
	// Table holds the table name of the clientinstalledcertificate in the database.
	Table = "client_installed_certificates"
)

// Columns holds all SQL columns for clientinstalledcertificate fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldClientID,
	FieldName,
	FieldSerialNumber,
	FieldFingerprintSha256,
	FieldStatus,
	FieldMessage,
	FieldInstalledAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-lcm/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusINSTALLED_CERT_STATUS_UNSPECIFIED is the default value of the Status enum.
const DefaultStatus = StatusINSTALLED_CERT_STATUS_UNSPECIFIED

// Status values.
const (
	StatusINSTALLED_CERT_STATUS_UNSPECIFIED Status = "INSTALLED_CERT_STATUS_UNSPECIFIED"
	StatusINSTALLED_CERT_STATUS_INSTALLED   Status = "INSTALLED_CERT_STATUS_INSTALLED"
	StatusINSTALLED_CERT_STATUS_FAILED      Status = "INSTALLED_CERT_STATUS_FAILED"
	StatusINSTALLED_CERT_STATUS_REMOVED     Status = "INSTALLED_CERT_STATUS_REMOVED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusINSTALLED_CERT_STATUS_UNSPECIFIED, StatusINSTALLED_CERT_STATUS_INSTALLED, StatusINSTALLED_CERT_STATUS_FAILED, StatusINSTALLED_CERT_STATUS_REMOVED:
		return nil
	default:
		return fmt.Errorf("clientinstalledcertificate: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ClientInstalledCertificate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySerialNumber orders the results by the serial_number field.
func BySerialNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSerialNumber, opts...).ToFunc()
}

// ByFingerprintSha256 orders the results by the fingerprint_sha256 field.
func ByFingerprintSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprintSha256, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByInstalledAt orders the results by the installed_at field.
func ByInstalledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstalledAt, opts...).ToFunc()
}
