// Code generated by ent, DO NOT EDIT.

package clientinstalledcertificate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-lcm/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldTenantID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldClientID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldName, v))
}

// SerialNumber applies equality check predicate on the "serial_number" field. It's identical to SerialNumberEQ.
func SerialNumber(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldSerialNumber, v))
}

// FingerprintSha256 applies equality check predicate on the "fingerprint_sha256" field. It's identical to FingerprintSha256EQ.
func FingerprintSha256(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldFingerprintSha256, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldMessage, v))
}

// InstalledAt applies equality check predicate on the "installed_at" field. It's identical to InstalledAtEQ.
func InstalledAt(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldInstalledAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotNull(FieldTenantID))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContainsFold(FieldClientID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContainsFold(FieldName, v))
}

// SerialNumberEQ applies the EQ predicate on the "serial_number" field.
func SerialNumberEQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldSerialNumber, v))
}

// SerialNumberNEQ applies the NEQ predicate on the "serial_number" field.
func SerialNumberNEQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldSerialNumber, v))
}

// SerialNumberIn applies the In predicate on the "serial_number" field.
func SerialNumberIn(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldSerialNumber, vs...))
}

// SerialNumberNotIn applies the NotIn predicate on the "serial_number" field.
func SerialNumberNotIn(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldSerialNumber, vs...))
}

// SerialNumberGT applies the GT predicate on the "serial_number" field.
func SerialNumberGT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldSerialNumber, v))
}

// SerialNumberGTE applies the GTE predicate on the "serial_number" field.
func SerialNumberGTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldSerialNumber, v))
}

// SerialNumberLT applies the LT predicate on the "serial_number" field.
func SerialNumberLT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldSerialNumber, v))
}

// SerialNumberLTE applies the LTE predicate on the "serial_number" field.
func SerialNumberLTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldSerialNumber, v))
}

// SerialNumberContains applies the Contains predicate on the "serial_number" field.
func SerialNumberContains(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContains(FieldSerialNumber, v))
}

// SerialNumberHasPrefix applies the HasPrefix predicate on the "serial_number" field.
func SerialNumberHasPrefix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasPrefix(FieldSerialNumber, v))
}

// SerialNumberHasSuffix applies the HasSuffix predicate on the "serial_number" field.
func SerialNumberHasSuffix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasSuffix(FieldSerialNumber, v))
}

// SerialNumberIsNil applies the IsNil predicate on the "serial_number" field.
func SerialNumberIsNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIsNull(FieldSerialNumber))
}

// SerialNumberNotNil applies the NotNil predicate on the "serial_number" field.
func SerialNumberNotNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotNull(FieldSerialNumber))
}

// SerialNumberEqualFold applies the EqualFold predicate on the "serial_number" field.
func SerialNumberEqualFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEqualFold(FieldSerialNumber, v))
}

// SerialNumberContainsFold applies the ContainsFold predicate on the "serial_number" field.
func SerialNumberContainsFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContainsFold(FieldSerialNumber, v))
}

// FingerprintSha256EQ applies the EQ predicate on the "fingerprint_sha256" field.
func FingerprintSha256EQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldFingerprintSha256, v))
}

// FingerprintSha256NEQ applies the NEQ predicate on the "fingerprint_sha256" field.
func FingerprintSha256NEQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldFingerprintSha256, v))
}

// FingerprintSha256In applies the In predicate on the "fingerprint_sha256" field.
func FingerprintSha256In(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldFingerprintSha256, vs...))
}

// FingerprintSha256NotIn applies the NotIn predicate on the "fingerprint_sha256" field.
func FingerprintSha256NotIn(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldFingerprintSha256, vs...))
}

// FingerprintSha256GT applies the GT predicate on the "fingerprint_sha256" field.
func FingerprintSha256GT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldFingerprintSha256, v))
}

// FingerprintSha256GTE applies the GTE predicate on the "fingerprint_sha256" field.
func FingerprintSha256GTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldFingerprintSha256, v))
}

// FingerprintSha256LT applies the LT predicate on the "fingerprint_sha256" field.
func FingerprintSha256LT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldFingerprintSha256, v))
}

// FingerprintSha256LTE applies the LTE predicate on the "fingerprint_sha256" field.
func FingerprintSha256LTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldFingerprintSha256, v))
}

// FingerprintSha256Contains applies the Contains predicate on the "fingerprint_sha256" field.
func FingerprintSha256Contains(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContains(FieldFingerprintSha256, v))
}

// FingerprintSha256HasPrefix applies the HasPrefix predicate on the "fingerprint_sha256" field.
func FingerprintSha256HasPrefix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasPrefix(FieldFingerprintSha256, v))
}

// FingerprintSha256HasSuffix applies the HasSuffix predicate on the "fingerprint_sha256" field.
func FingerprintSha256HasSuffix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasSuffix(FieldFingerprintSha256, v))
}

// FingerprintSha256IsNil applies the IsNil predicate on the "fingerprint_sha256" field.
func FingerprintSha256IsNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIsNull(FieldFingerprintSha256))
}

// FingerprintSha256NotNil applies the NotNil predicate on the "fingerprint_sha256" field.
func FingerprintSha256NotNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotNull(FieldFingerprintSha256))
}

// FingerprintSha256EqualFold applies the EqualFold predicate on the "fingerprint_sha256" field.
func FingerprintSha256EqualFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEqualFold(FieldFingerprintSha256, v))
}

// FingerprintSha256ContainsFold applies the ContainsFold predicate on the "fingerprint_sha256" field.
func FingerprintSha256ContainsFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContainsFold(FieldFingerprintSha256, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldStatus, vs...))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldContainsFold(FieldMessage, v))
}

// InstalledAtEQ applies the EQ predicate on the "installed_at" field.
func InstalledAtEQ(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldEQ(FieldInstalledAt, v))
}

// InstalledAtNEQ applies the NEQ predicate on the "installed_at" field.
func InstalledAtNEQ(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNEQ(FieldInstalledAt, v))
}

// InstalledAtIn applies the In predicate on the "installed_at" field.
func InstalledAtIn(vs ...time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIn(FieldInstalledAt, vs...))
}

// InstalledAtNotIn applies the NotIn predicate on the "installed_at" field.
func InstalledAtNotIn(vs ...time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotIn(FieldInstalledAt, vs...))
}

// InstalledAtGT applies the GT predicate on the "installed_at" field.
func InstalledAtGT(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGT(FieldInstalledAt, v))
}

// InstalledAtGTE applies the GTE predicate on the "installed_at" field.
func InstalledAtGTE(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldGTE(FieldInstalledAt, v))
}

// InstalledAtLT applies the LT predicate on the "installed_at" field.
func InstalledAtLT(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLT(FieldInstalledAt, v))
}

// InstalledAtLTE applies the LTE predicate on the "installed_at" field.
func InstalledAtLTE(v time.Time) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldLTE(FieldInstalledAt, v))
}

// InstalledAtIsNil applies the IsNil predicate on the "installed_at" field.
func InstalledAtIsNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldIsNull(FieldInstalledAt))
}

// InstalledAtNotNil applies the NotNil predicate on the "installed_at" field.
func InstalledAtNotNil() predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.FieldNotNull(FieldInstalledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClientInstalledCertificate) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClientInstalledCertificate) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClientInstalledCertificate) predicate.ClientInstalledCertificate {
	return predicate.ClientInstalledCertificate(sql.NotPredicates(p))
}
