/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/lcm/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GetStatistics returns comprehensive statistics about the LCM system */
        get: operations["LcmStatisticsService_GetStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lcm/statistics/tenant/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GetTenantStatistics returns statistics for a specific tenant */
        get: operations["LcmStatisticsService_GetTenantStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certificate-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List certificate jobs for the authenticated client */
        get: operations["LcmCertificateJobService_ListJobs"];
        put?: never;
        /** @description Request a new certificate (async - returns job ID immediately) */
        post: operations["LcmCertificateJobService_RequestCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certificate-jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel a pending certificate job */
        post: operations["LcmCertificateJobService_CancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certificate-jobs/{jobId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the result of a completed certificate job */
        get: operations["LcmCertificateJobService_GetJobResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certificate-jobs/{jobId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the status of a certificate job */
        get: operations["LcmCertificateJobService_GetJobStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certificate-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Grant permission to another client to access a certificate */
        post: operations["CertificatePermissionService_GrantPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certificate-permissions/accessible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all certificates accessible to the authenticated client (grants received) */
        get: operations["CertificatePermissionService_ListAccessibleCertificates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certificate-permissions/{certificateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all permissions for a certificate (as owner) */
        get: operations["CertificatePermissionService_ListPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certificate-permissions/{certificateId}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Check if the authenticated client has permission to access a certificate */
        get: operations["CertificatePermissionService_CheckPermission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/certificate-permissions/{certificateId}/grantees/{granteeClientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Revoke a previously granted permission */
        delete: operations["CertificatePermissionService_RevokePermission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dns-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description DNS challenge provider information */
        get: operations["LcmIssuerService_ListDnsProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dns-providers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LcmIssuerService_GetDnsProviderInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SystemService_HealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/issuers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ACME issuer management (authenticated) */
        get: operations["LcmIssuerService_ListIssuers"];
        put?: never;
        post: operations["LcmIssuerService_CreateIssuer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/issuers/{issuerName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LcmIssuerService_GetIssuerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/issuers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["LcmIssuerService_UpdateIssuer"];
        post?: never;
        delete: operations["LcmIssuerService_DeleteIssuer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant-secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List tenant secrets */
        get: operations["TenantSecretService_ListTenantSecrets"];
        put?: never;
        /** @description Create a new tenant secret */
        post: operations["TenantSecretService_CreateTenantSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant-secrets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a tenant secret by ID */
        get: operations["TenantSecretService_GetTenantSecret"];
        /** @description Update a tenant secret */
        put: operations["TenantSecretService_UpdateTenantSecret"];
        post?: never;
        /** @description Delete a tenant secret */
        delete: operations["TenantSecretService_DeleteTenantSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant-secrets/{id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Rotate a tenant secret */
        post: operations["TenantSecretService_RotateTenantSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Certificate accessible via permission grant */
        AccessibleCertificate: {
            certificateId?: string;
            ownerClientId?: string;
            commonName?: string;
            dnsNames?: string[];
            issuerName?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            permissionType?: "PERMISSION_TYPE_UNSPECIFIED" | "PERMISSION_TYPE_READ" | "PERMISSION_TYPE_DOWNLOAD" | "PERMISSION_TYPE_FULL";
            grantedBy?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            certificateExpiresAt?: string;
            /** Format: date-time */
            grantedAt?: string;
        };
        AcmeIssuer: {
            email?: string;
            endpoint?: string;
            keyType?: string;
            /** Format: int32 */
            keySize?: number;
            /** Format: int32 */
            maxRetries?: number;
            baseDelay?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            challengeType?: "HTTP" | "DNS";
            providerName?: string;
            providerConfig?: {
                [key: string]: string;
            };
            /** @description External Account Binding (EAB) for ACME providers that require it (e.g., ZeroSSL, Google Trust Services) */
            eabKid?: string;
            eabHmacKey?: string;
        };
        /** @description Job summary info for listing */
        CertificateJobInfo: {
            jobId?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "CERTIFICATE_JOB_STATUS_UNSPECIFIED" | "CERTIFICATE_JOB_STATUS_PENDING" | "CERTIFICATE_JOB_STATUS_PROCESSING" | "CERTIFICATE_JOB_STATUS_COMPLETED" | "CERTIFICATE_JOB_STATUS_FAILED" | "CERTIFICATE_JOB_STATUS_CANCELLED";
            issuerName?: string;
            issuerType?: string;
            commonName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            completedAt?: string;
            errorMessage?: string;
        };
        /** @description CertificatePermission represents a permission grant */
        CertificatePermission: {
            /** Format: uint32 */
            id?: number;
            certificateId?: string;
            /** Format: uint32 */
            granteeClientId?: number;
            granteeClientName?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            permissionType?: "PERMISSION_TYPE_UNSPECIFIED" | "PERMISSION_TYPE_READ" | "PERMISSION_TYPE_DOWNLOAD" | "PERMISSION_TYPE_FULL";
            grantedBy?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description CertificateStatistics contains statistics about certificates */
        CertificateStatistics: {
            /** @description Total number of certificates */
            totalCount?: string;
            /** @description Number of active certificates */
            activeCount?: string;
            /** @description Number of expired certificates */
            expiredCount?: string;
            /** @description Number of revoked certificates */
            revokedCount?: string;
            /** @description Number of suspended certificates */
            suspendedCount?: string;
            /** @description Number of certificates expiring soon */
            expireSoonCount?: string;
            /**
             * Format: int32
             * @description Days threshold used for expire soon calculation
             */
            expireSoonDays?: number;
            /** @description Number of wildcard certificates */
            wildcardCount?: string;
            /** @description Certificates by type */
            byType?: components["schemas"]["CertificateTypeBreakdown"];
            /** @description Certificates grouped by issuer */
            byIssuer?: components["schemas"]["IssuerCertificateCount"][];
        };
        /** @description CertificateTypeBreakdown provides certificate counts by type */
        CertificateTypeBreakdown: {
            /** @description Number of client certificates */
            clientCerts?: string;
            /** @description Number of internal certificates */
            internalCerts?: string;
            /** @description Number of CA certificates */
            caCerts?: string;
        };
        /** @description Response for permission check */
        CheckPermissionResponse: {
            hasPermission?: boolean;
            /** @description True if the caller owns the certificate (not via grant) */
            isOwner?: boolean;
            /**
             * Format: enum
             * @description The actual permission level if granted (may be higher than required)
             * @enum {string}
             */
            grantedPermission?: "PERMISSION_TYPE_UNSPECIFIED" | "PERMISSION_TYPE_READ" | "PERMISSION_TYPE_DOWNLOAD" | "PERMISSION_TYPE_FULL";
        };
        /** @description ClientStatistics contains statistics about LCM clients */
        ClientStatistics: {
            /** @description Total number of registered clients */
            totalCount?: string;
            /** @description Number of active clients */
            activeCount?: string;
            /** @description Number of disabled clients */
            disabledCount?: string;
            /** @description Number of suspended clients */
            suspendedCount?: string;
            /** @description Clients grouped by status */
            byStatus?: {
                [key: string]: string;
            };
        };
        /** @description Issuer creation and management messages */
        CreateIssuerRequest: {
            name?: string;
            type?: string;
            keyType?: string;
            description?: string;
            selfIssuer?: components["schemas"]["SelfIssuer"];
            acmeIssuer?: components["schemas"]["AcmeIssuer"];
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "ISSUER_STATUS_UNSPECIFIED" | "ISSUER_STATUS_ACTIVE" | "ISSUER_STATUS_DISABLED" | "ISSUER_STATUS_ERROR";
        };
        CreateIssuerResponse: {
            issuer?: components["schemas"]["IssuerInfo"];
        };
        /** @description Create a new tenant secret */
        CreateTenantSecretRequest: {
            /** Format: uint32 */
            tenantId: number;
            secret: string;
            description?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        CreateTenantSecretResponse: {
            tenantSecret?: components["schemas"]["TenantSecret"];
        };
        DnsProviderInfo: {
            name?: string;
            description?: string;
            requiredFields?: string[];
            optionalFields?: string[];
        };
        GetIssuerInfoResponse: {
            issuer?: components["schemas"]["IssuerInfo"];
        };
        /** @description Job result response */
        GetJobResultResponse: {
            jobId?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "CERTIFICATE_JOB_STATUS_UNSPECIFIED" | "CERTIFICATE_JOB_STATUS_PENDING" | "CERTIFICATE_JOB_STATUS_PROCESSING" | "CERTIFICATE_JOB_STATUS_COMPLETED" | "CERTIFICATE_JOB_STATUS_FAILED" | "CERTIFICATE_JOB_STATUS_CANCELLED";
            /** @description Certificate data (only present if job is completed) */
            certificatePem?: string;
            caCertificatePem?: string;
            privateKeyPem?: string;
            serialNumber?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            issuedAt?: string;
            /** @description Error info (only present if job failed) */
            errorMessage?: string;
            /** @description Certificate request data */
            csrPem?: string;
            keyType?: string;
            /** Format: int32 */
            keySize?: number;
            serverGeneratedKey?: boolean;
        };
        /** @description Job status response */
        GetJobStatusResponse: {
            jobId?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "CERTIFICATE_JOB_STATUS_UNSPECIFIED" | "CERTIFICATE_JOB_STATUS_PENDING" | "CERTIFICATE_JOB_STATUS_PROCESSING" | "CERTIFICATE_JOB_STATUS_COMPLETED" | "CERTIFICATE_JOB_STATUS_FAILED" | "CERTIFICATE_JOB_STATUS_CANCELLED";
            issuerName?: string;
            issuerType?: string;
            commonName?: string;
            dnsNames?: string[];
            ipAddresses?: string[];
            errorMessage?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        /** @description GetStatisticsResponse is the response message for GetStatistics */
        GetStatisticsResponse: {
            /** @description Overall certificate statistics (DEPRECATED: use issued_certificates and mtls_certificates instead) */
            certificates?: components["schemas"]["CertificateStatistics"];
            /** @description Client statistics */
            clients?: components["schemas"]["ClientStatistics"];
            /** @description Issuer statistics */
            issuers?: components["schemas"]["IssuerStatistics"];
            /** @description Certificate job statistics */
            jobs?: components["schemas"]["JobStatistics"];
            /** @description Recent errors/failures */
            recentErrors?: components["schemas"]["RecentError"][];
            /** @description Per-tenant breakdown (only for platform admin requests) */
            tenantBreakdown?: components["schemas"]["TenantStatistics"][];
            /**
             * Format: date-time
             * @description Statistics generation timestamp
             */
            generatedAt?: string;
            /** @description Issued certificate statistics (certificates issued to clients - the main certificates) */
            issuedCertificates?: components["schemas"]["IssuedCertificateStatistics"];
            /** @description MTLS certificate statistics (certificates used for mTLS authentication - internal use) */
            mtlsCertificates?: components["schemas"]["MtlsCertificateStatistics"];
        };
        GetTenantSecretResponse: {
            tenantSecret?: components["schemas"]["TenantSecret"];
        };
        /** @description Request to grant permission */
        GrantPermissionRequest: {
            /** @description ID of the certificate to share */
            certificateId: string;
            /** @description Client ID of the grantee (the client receiving access) */
            granteeClientId: string;
            /**
             * Format: enum
             * @description Type of permission to grant
             * @enum {string}
             */
            permissionType: "PERMISSION_TYPE_UNSPECIFIED" | "PERMISSION_TYPE_READ" | "PERMISSION_TYPE_DOWNLOAD" | "PERMISSION_TYPE_FULL";
            /**
             * Format: date-time
             * @description Optional expiration time for the permission
             */
            expiresAt?: string;
        };
        /** @description Response after granting permission */
        GrantPermissionResponse: {
            permission?: components["schemas"]["CertificatePermission"];
        };
        HealthCheckResponse: {
            status?: boolean;
            message?: string;
        };
        /**
         * @description IssuedCertificateStatistics contains statistics about certificates issued to clients
         *      These are the main certificates that users request and manage
         */
        IssuedCertificateStatistics: {
            /** @description Total number of issued certificates */
            totalCount?: string;
            /** @description Number of active certificates (status=issued) */
            activeCount?: string;
            /** @description Number of expired certificates */
            expiredCount?: string;
            /** @description Number of revoked certificates */
            revokedCount?: string;
            /** @description Number of pending certificates */
            pendingCount?: string;
            /** @description Number of certificates being processed */
            processingCount?: string;
            /** @description Number of failed certificate requests */
            failedCount?: string;
            /** @description Number of certificates expiring soon */
            expireSoonCount?: string;
            /**
             * Format: int32
             * @description Days threshold used for expire soon calculation
             */
            expireSoonDays?: number;
            /** @description Number of wildcard certificates */
            wildcardCount?: string;
            /** @description Number of certificates with auto-renewal enabled */
            autoRenewEnabledCount?: string;
            /** @description Certificates grouped by issuer type */
            byIssuerType?: {
                [key: string]: string;
            };
        };
        /** @description IssuerCertificateCount represents certificate count for an issuer */
        IssuerCertificateCount: {
            /** @description Issuer name */
            issuerName?: string;
            /** @description Issuer type (self-signed, acme) */
            issuerType?: string;
            /** @description Total certificates issued by this issuer */
            totalCount?: string;
            /** @description Active certificates */
            activeCount?: string;
            /** @description Expired certificates */
            expiredCount?: string;
            /** @description Revoked certificates */
            revokedCount?: string;
        };
        IssuerInfo: {
            name?: string;
            type?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "ISSUER_STATUS_UNSPECIFIED" | "ISSUER_STATUS_ACTIVE" | "ISSUER_STATUS_DISABLED" | "ISSUER_STATUS_ERROR";
            description?: string;
            config?: {
                [key: string]: string;
            };
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
        };
        /** @description IssuerStatistics contains statistics about certificate issuers */
        IssuerStatistics: {
            /** @description Total number of issuers */
            totalCount?: string;
            /** @description Number of active issuers */
            activeCount?: string;
            /** @description Number of disabled issuers */
            disabledCount?: string;
            /** @description Number of issuers in error state */
            errorCount?: string;
            /** @description Issuers by type */
            byType?: {
                [key: string]: string;
            };
        };
        /** @description JobStatistics contains statistics about certificate jobs */
        JobStatistics: {
            /** @description Total number of jobs */
            totalCount?: string;
            /** @description Number of pending jobs */
            pendingCount?: string;
            /** @description Number of processing jobs */
            processingCount?: string;
            /** @description Number of completed jobs */
            completedCount?: string;
            /** @description Number of failed jobs */
            failedCount?: string;
            /** @description Number of cancelled jobs */
            cancelledCount?: string;
            /** @description Jobs in the last 24 hours */
            last24Hours?: components["schemas"]["JobTimeBreakdown"];
            /** @description Jobs in the last 7 days */
            last7Days?: components["schemas"]["JobTimeBreakdown"];
        };
        /** @description JobTimeBreakdown provides job counts within a time period */
        JobTimeBreakdown: {
            /** @description Total jobs in period */
            total?: string;
            /** @description Successful jobs */
            succeeded?: string;
            /** @description Failed jobs */
            failed?: string;
            /**
             * Format: double
             * @description Success rate percentage (0-100)
             */
            successRate?: number;
        };
        /** @description Response listing accessible certificates */
        ListAccessibleCertificatesResponse: {
            certificates?: components["schemas"]["AccessibleCertificate"][];
            /** Format: uint32 */
            total?: number;
        };
        /** @description DNS Provider messages for DNS challenge support */
        ListDnsProvidersResponse: {
            providers?: components["schemas"]["DnsProviderInfo"][];
        };
        ListIssuersResponse: {
            issuers?: components["schemas"]["IssuerInfo"][];
        };
        /** @description List jobs response */
        ListJobsResponse: {
            jobs?: components["schemas"]["CertificateJobInfo"][];
            /** Format: uint32 */
            total?: number;
        };
        /** @description Response listing all permissions for a certificate */
        ListPermissionsResponse: {
            permissions?: components["schemas"]["CertificatePermission"][];
            /** Format: uint32 */
            total?: number;
        };
        ListTenantSecretsResponse: {
            items?: components["schemas"]["TenantSecret"][];
            total?: string;
        };
        /**
         * @description MtlsCertificateStatistics contains statistics about mTLS authentication certificates
         *      These are internal certificates used for service-to-service authentication
         */
        MtlsCertificateStatistics: {
            /** @description Total number of mTLS certificates */
            totalCount?: string;
            /** @description Number of active mTLS certificates */
            activeCount?: string;
            /** @description Number of expired mTLS certificates */
            expiredCount?: string;
            /** @description Number of revoked mTLS certificates */
            revokedCount?: string;
            /** @description Number of suspended mTLS certificates */
            suspendedCount?: string;
            /** @description Number of mTLS certificates expiring soon */
            expireSoonCount?: string;
            /**
             * Format: int32
             * @description Days threshold used for expire soon calculation
             */
            expireSoonDays?: number;
            /** @description Certificates by type (client, internal) */
            byType?: components["schemas"]["CertificateTypeBreakdown"];
        };
        /** @description RecentError represents a recent certificate issuance failure */
        RecentError: {
            /**
             * Format: date-time
             * @description Error timestamp
             */
            occurredAt?: string;
            /** @description Job ID that failed */
            jobId?: string;
            /** @description Client ID that requested the certificate */
            clientId?: string;
            /** @description Common name of the requested certificate */
            commonName?: string;
            /** @description Issuer name */
            issuerName?: string;
            /** @description Error message */
            errorMessage?: string;
            /**
             * Format: uint32
             * @description Tenant ID
             */
            tenantId?: number;
        };
        /** @description Request to create a new certificate */
        RequestCertificateRequest: {
            /** @description Issuer to use for certificate generation */
            issuerName: string;
            /** @description Common name for the certificate */
            commonName: string;
            /** @description DNS names for Subject Alternative Names */
            dnsNames?: string[];
            /** @description IP addresses for Subject Alternative Names */
            ipAddresses?: string[];
            /** @description Optional CSR (if not provided, key will be generated) */
            csrPem?: string;
            /** @description Key type (only used if CSR is not provided) */
            keyType?: string;
            /**
             * Format: int32
             * @description Key size in bits (only used if CSR is not provided)
             */
            keySize?: number;
            /**
             * Format: int32
             * @description Certificate validity in days
             */
            validityDays?: number;
            /** @description Custom metadata */
            metadata?: {
                [key: string]: string;
            };
        };
        /** @description Response with job ID for tracking */
        RequestCertificateResponse: {
            jobId?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "CERTIFICATE_JOB_STATUS_UNSPECIFIED" | "CERTIFICATE_JOB_STATUS_PENDING" | "CERTIFICATE_JOB_STATUS_PROCESSING" | "CERTIFICATE_JOB_STATUS_COMPLETED" | "CERTIFICATE_JOB_STATUS_FAILED" | "CERTIFICATE_JOB_STATUS_CANCELLED";
            message?: string;
        };
        /** @description Rotate a tenant secret (create new secret, optionally disable old) */
        RotateTenantSecretRequest: {
            /** Format: uint32 */
            id: number;
            newSecret: string;
            disableOld?: boolean;
        };
        RotateTenantSecretResponse: {
            newSecret?: components["schemas"]["TenantSecret"];
            oldSecret?: components["schemas"]["TenantSecret"];
        };
        SelfIssuer: {
            commonName?: string;
            dnsNames?: string[];
            ipAddresses?: string[];
            /** @description CA certificate configuration */
            caCommonName?: string;
            caOrganization?: string;
            caOrganizationalUnit?: string;
            caCountry?: string;
            caProvince?: string;
            caLocality?: string;
            /** Format: int32 */
            caValidityDays?: number;
        };
        /** @description TenantSecret entity - maps shared secrets to tenants */
        TenantSecret: {
            /** Format: uint32 */
            id?: number;
            /** Format: uint32 */
            tenantId?: number;
            description?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "TENANT_SECRET_STATUS_UNSPECIFIED" | "TENANT_SECRET_STATUS_ACTIVE" | "TENANT_SECRET_STATUS_DISABLED";
            /** Format: date-time */
            expiresAt?: string;
            /** Format: uint32 */
            createdBy?: number;
            /** Format: uint32 */
            updatedBy?: number;
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
        };
        /** @description TenantStatistics provides statistics for a specific tenant */
        TenantStatistics: {
            /**
             * Format: uint32
             * @description Tenant ID
             */
            tenantId?: number;
            /** @description Certificate statistics for this tenant (DEPRECATED) */
            certificates?: components["schemas"]["CertificateStatistics"];
            /** @description Client statistics for this tenant */
            clients?: components["schemas"]["ClientStatistics"];
            /** @description Issuer statistics for this tenant */
            issuers?: components["schemas"]["IssuerStatistics"];
            /** @description Job statistics for this tenant */
            jobs?: components["schemas"]["JobStatistics"];
            /** @description Issued certificate statistics for this tenant */
            issuedCertificates?: components["schemas"]["IssuedCertificateStatistics"];
            /** @description MTLS certificate statistics for this tenant */
            mtlsCertificates?: components["schemas"]["MtlsCertificateStatistics"];
        };
        UpdateIssuerRequest: {
            name?: string;
            type?: string;
            keyType?: string;
            description?: string;
            selfIssuer?: components["schemas"]["SelfIssuer"];
            acmeIssuer?: components["schemas"]["AcmeIssuer"];
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "ISSUER_STATUS_UNSPECIFIED" | "ISSUER_STATUS_ACTIVE" | "ISSUER_STATUS_DISABLED" | "ISSUER_STATUS_ERROR";
        };
        /** @description Update a tenant secret (description, status, expiry only - secret cannot be updated) */
        UpdateTenantSecretRequest: {
            /** Format: uint32 */
            id: number;
            description?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "TENANT_SECRET_STATUS_UNSPECIFIED" | "TENANT_SECRET_STATUS_ACTIVE" | "TENANT_SECRET_STATUS_DISABLED";
            /** Format: date-time */
            expiresAt?: string;
        };
        UpdateTenantSecretResponse: {
            tenantSecret?: components["schemas"]["TenantSecret"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    LcmStatisticsService_GetStatistics: {
        parameters: {
            query?: {
                /** @description Number of days to consider for "expire soon" certificates (default: 30) */
                expireSoonDays?: number;
                /** @description Number of recent errors to return (default: 10) */
                recentErrorsLimit?: number;
                /** @description Filter by specific tenant ID (optional, admin only) */
                tenantId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStatisticsResponse"];
                };
            };
        };
    };
    LcmStatisticsService_GetTenantStatistics: {
        parameters: {
            query?: {
                /** @description Number of days for expire soon calculation (default: 30) */
                expireSoonDays?: number;
            };
            header?: never;
            path: {
                /** @description Tenant ID to get statistics for */
                tenantId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantStatistics"];
                };
            };
        };
    };
    LcmCertificateJobService_ListJobs: {
        parameters: {
            query?: {
                status?: "CERTIFICATE_JOB_STATUS_UNSPECIFIED" | "CERTIFICATE_JOB_STATUS_PENDING" | "CERTIFICATE_JOB_STATUS_PROCESSING" | "CERTIFICATE_JOB_STATUS_COMPLETED" | "CERTIFICATE_JOB_STATUS_FAILED" | "CERTIFICATE_JOB_STATUS_CANCELLED";
                page?: number;
                pageSize?: number;
                issuerName?: string;
                tenantId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListJobsResponse"];
                };
            };
        };
    };
    LcmCertificateJobService_RequestCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCertificateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCertificateResponse"];
                };
            };
        };
    };
    LcmCertificateJobService_CancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LcmCertificateJobService_GetJobResult: {
        parameters: {
            query?: {
                /** @description Whether to include the private key in the response */
                includePrivateKey?: boolean;
            };
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetJobResultResponse"];
                };
            };
        };
    };
    LcmCertificateJobService_GetJobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetJobStatusResponse"];
                };
            };
        };
    };
    CertificatePermissionService_GrantPermission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantPermissionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantPermissionResponse"];
                };
            };
        };
    };
    CertificatePermissionService_ListAccessibleCertificates: {
        parameters: {
            query?: {
                /** @description Filter by permission type */
                permissionType?: "PERMISSION_TYPE_UNSPECIFIED" | "PERMISSION_TYPE_READ" | "PERMISSION_TYPE_DOWNLOAD" | "PERMISSION_TYPE_FULL";
                /** @description Include expired permissions */
                includeExpired?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAccessibleCertificatesResponse"];
                };
            };
        };
    };
    CertificatePermissionService_ListPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the certificate (caller must be the owner) */
                certificateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPermissionsResponse"];
                };
            };
        };
    };
    CertificatePermissionService_CheckPermission: {
        parameters: {
            query?: {
                /** @description Required permission type */
                requiredPermission?: "PERMISSION_TYPE_UNSPECIFIED" | "PERMISSION_TYPE_READ" | "PERMISSION_TYPE_DOWNLOAD" | "PERMISSION_TYPE_FULL";
            };
            header?: never;
            path: {
                /** @description ID of the certificate to check */
                certificateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckPermissionResponse"];
                };
            };
        };
    };
    CertificatePermissionService_RevokePermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the certificate */
                certificateId: string;
                /** @description Client ID of the grantee whose permission is being revoked */
                granteeClientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LcmIssuerService_ListDnsProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDnsProvidersResponse"];
                };
            };
        };
    };
    LcmIssuerService_GetDnsProviderInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsProviderInfo"];
                };
            };
        };
    };
    SystemService_HealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    LcmIssuerService_ListIssuers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListIssuersResponse"];
                };
            };
        };
    };
    LcmIssuerService_CreateIssuer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIssuerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateIssuerResponse"];
                };
            };
        };
    };
    LcmIssuerService_GetIssuerInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issuerName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetIssuerInfoResponse"];
                };
            };
        };
    };
    LcmIssuerService_UpdateIssuer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssuerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LcmIssuerService_DeleteIssuer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantSecretService_ListTenantSecrets: {
        parameters: {
            query?: {
                tenantId?: number;
                status?: "TENANT_SECRET_STATUS_UNSPECIFIED" | "TENANT_SECRET_STATUS_ACTIVE" | "TENANT_SECRET_STATUS_DISABLED";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTenantSecretsResponse"];
                };
            };
        };
    };
    TenantSecretService_CreateTenantSecret: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantSecretRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTenantSecretResponse"];
                };
            };
        };
    };
    TenantSecretService_GetTenantSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTenantSecretResponse"];
                };
            };
        };
    };
    TenantSecretService_UpdateTenantSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantSecretRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateTenantSecretResponse"];
                };
            };
        };
    };
    TenantSecretService_DeleteTenantSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantSecretService_RotateTenantSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateTenantSecretRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateTenantSecretResponse"];
                };
            };
        };
    };
}
