// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: lcm/v1/lcm.proto

// lcm.v1 is the service-to-service and workload-agent API of the certificate &
// SVID lifecycle module. It is NOT proxied by the gateway: callers are
// authenticated services or workloads on the Freya SPIFFE mTLS channel, policed
// by the module's deploy/policy.yaml. The tenant comes from the request and the
// actor from the verified SPIFFE identity. Responses never carry CA/issuer/DNS
// keys; a workload private key is returned only when the module generated it.

package lcmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SVID_Issue_FullMethodName          = "/lcm.v1.SVID/Issue"
	SVID_Renew_FullMethodName          = "/lcm.v1.SVID/Renew"
	SVID_Revoke_FullMethodName         = "/lcm.v1.SVID/Revoke"
	SVID_Verify_FullMethodName         = "/lcm.v1.SVID/Verify"
	SVID_GetTrustBundle_FullMethodName = "/lcm.v1.SVID/GetTrustBundle"
)

// SVIDClient is the client API for SVID service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SVID issues, renews, revokes and verifies certificates for modules.
type SVIDClient interface {
	// Issue mints an SVID for a SPIFFE id the caller is entitled to (its own id,
	// a use grant, or an enrollment token). csr_pem signs the caller's key;
	// otherwise the module generates the key and returns it once.
	Issue(ctx context.Context, in *IssueRequest, opts ...grpc.CallOption) (*CertificateBundle, error)
	// Renew reissues an existing certificate with the same SPIFFE id.
	Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*CertificateBundle, error)
	// Revoke revokes a certificate and publishes the revocation.
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
	// Verify reports whether a certificate is currently valid (not expired, not revoked).
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// GetTrustBundle returns the roots for a trust domain.
	GetTrustBundle(ctx context.Context, in *TrustBundleRequest, opts ...grpc.CallOption) (*TrustBundleResponse, error)
}

type sVIDClient struct {
	cc grpc.ClientConnInterface
}

func NewSVIDClient(cc grpc.ClientConnInterface) SVIDClient {
	return &sVIDClient{cc}
}

func (c *sVIDClient) Issue(ctx context.Context, in *IssueRequest, opts ...grpc.CallOption) (*CertificateBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateBundle)
	err := c.cc.Invoke(ctx, SVID_Issue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sVIDClient) Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*CertificateBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateBundle)
	err := c.cc.Invoke(ctx, SVID_Renew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sVIDClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, SVID_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sVIDClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, SVID_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sVIDClient) GetTrustBundle(ctx context.Context, in *TrustBundleRequest, opts ...grpc.CallOption) (*TrustBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrustBundleResponse)
	err := c.cc.Invoke(ctx, SVID_GetTrustBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SVIDServer is the server API for SVID service.
// All implementations must embed UnimplementedSVIDServer
// for forward compatibility.
//
// SVID issues, renews, revokes and verifies certificates for modules.
type SVIDServer interface {
	// Issue mints an SVID for a SPIFFE id the caller is entitled to (its own id,
	// a use grant, or an enrollment token). csr_pem signs the caller's key;
	// otherwise the module generates the key and returns it once.
	Issue(context.Context, *IssueRequest) (*CertificateBundle, error)
	// Renew reissues an existing certificate with the same SPIFFE id.
	Renew(context.Context, *RenewRequest) (*CertificateBundle, error)
	// Revoke revokes a certificate and publishes the revocation.
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
	// Verify reports whether a certificate is currently valid (not expired, not revoked).
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	// GetTrustBundle returns the roots for a trust domain.
	GetTrustBundle(context.Context, *TrustBundleRequest) (*TrustBundleResponse, error)
	mustEmbedUnimplementedSVIDServer()
}

// UnimplementedSVIDServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSVIDServer struct{}

func (UnimplementedSVIDServer) Issue(context.Context, *IssueRequest) (*CertificateBundle, error) {
	return nil, status.Error(codes.Unimplemented, "method Issue not implemented")
}
func (UnimplementedSVIDServer) Renew(context.Context, *RenewRequest) (*CertificateBundle, error) {
	return nil, status.Error(codes.Unimplemented, "method Renew not implemented")
}
func (UnimplementedSVIDServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedSVIDServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedSVIDServer) GetTrustBundle(context.Context, *TrustBundleRequest) (*TrustBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrustBundle not implemented")
}
func (UnimplementedSVIDServer) mustEmbedUnimplementedSVIDServer() {}
func (UnimplementedSVIDServer) testEmbeddedByValue()              {}

// UnsafeSVIDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SVIDServer will
// result in compilation errors.
type UnsafeSVIDServer interface {
	mustEmbedUnimplementedSVIDServer()
}

func RegisterSVIDServer(s grpc.ServiceRegistrar, srv SVIDServer) {
	// If the following call panics, it indicates UnimplementedSVIDServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SVID_ServiceDesc, srv)
}

func _SVID_Issue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SVIDServer).Issue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SVID_Issue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SVIDServer).Issue(ctx, req.(*IssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SVID_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SVIDServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SVID_Renew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SVIDServer).Renew(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SVID_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SVIDServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SVID_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SVIDServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SVID_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SVIDServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SVID_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SVIDServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SVID_GetTrustBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrustBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SVIDServer).GetTrustBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SVID_GetTrustBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SVIDServer).GetTrustBundle(ctx, req.(*TrustBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SVID_ServiceDesc is the grpc.ServiceDesc for SVID service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SVID_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lcm.v1.SVID",
	HandlerType: (*SVIDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Issue",
			Handler:    _SVID_Issue_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _SVID_Renew_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _SVID_Revoke_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _SVID_Verify_Handler,
		},
		{
			MethodName: "GetTrustBundle",
			Handler:    _SVID_GetTrustBundle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lcm/v1/lcm.proto",
}

const (
	Enrollment_Enroll_FullMethodName = "/lcm.v1.Enrollment/Enroll"
)

// EnrollmentClient is the client API for Enrollment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Enrollment lets a new workload obtain its first SVID with an auth-minted token.
type EnrollmentClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*CertificateBundle, error)
}

type enrollmentClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentClient(cc grpc.ClientConnInterface) EnrollmentClient {
	return &enrollmentClient{cc}
}

func (c *enrollmentClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*CertificateBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateBundle)
	err := c.cc.Invoke(ctx, Enrollment_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServer is the server API for Enrollment service.
// All implementations must embed UnimplementedEnrollmentServer
// for forward compatibility.
//
// Enrollment lets a new workload obtain its first SVID with an auth-minted token.
type EnrollmentServer interface {
	Enroll(context.Context, *EnrollRequest) (*CertificateBundle, error)
	mustEmbedUnimplementedEnrollmentServer()
}

// UnimplementedEnrollmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServer struct{}

func (UnimplementedEnrollmentServer) Enroll(context.Context, *EnrollRequest) (*CertificateBundle, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedEnrollmentServer) mustEmbedUnimplementedEnrollmentServer() {}
func (UnimplementedEnrollmentServer) testEmbeddedByValue()                    {}

// UnsafeEnrollmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServer will
// result in compilation errors.
type UnsafeEnrollmentServer interface {
	mustEmbedUnimplementedEnrollmentServer()
}

func RegisterEnrollmentServer(s grpc.ServiceRegistrar, srv EnrollmentServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Enrollment_ServiceDesc, srv)
}

func _Enrollment_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrollment_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Enrollment_ServiceDesc is the grpc.ServiceDesc for Enrollment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Enrollment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lcm.v1.Enrollment",
	HandlerType: (*EnrollmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _Enrollment_Enroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lcm/v1/lcm.proto",
}

const (
	Events_Publish_FullMethodName = "/lcm.v1.Events/Publish"
)

// EventsClient is the client API for Events service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Events publishes lifecycle events for other modules (fan-out via the tenant stream).
type EventsClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type eventsClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsClient(cc grpc.ClientConnInterface) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, Events_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsServer is the server API for Events service.
// All implementations must embed UnimplementedEventsServer
// for forward compatibility.
//
// Events publishes lifecycle events for other modules (fan-out via the tenant stream).
type EventsServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	mustEmbedUnimplementedEventsServer()
}

// UnimplementedEventsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventsServer struct{}

func (UnimplementedEventsServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedEventsServer) mustEmbedUnimplementedEventsServer() {}
func (UnimplementedEventsServer) testEmbeddedByValue()                {}

// UnsafeEventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventsServer will
// result in compilation errors.
type UnsafeEventsServer interface {
	mustEmbedUnimplementedEventsServer()
}

func RegisterEventsServer(s grpc.ServiceRegistrar, srv EventsServer) {
	// If the following call panics, it indicates UnimplementedEventsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Events_ServiceDesc, srv)
}

func _Events_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Events_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Events_ServiceDesc is the grpc.ServiceDesc for Events service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Events_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lcm.v1.Events",
	HandlerType: (*EventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Events_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lcm/v1/lcm.proto",
}

const (
	Agent_Watch_FullMethodName = "/lcm.v1.Agent/Watch"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent streams live certificate updates to a workload agent so it rotates without downtime.
type AgentClient interface {
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CertificateUpdate], error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CertificateUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], Agent_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, CertificateUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_WatchClient = grpc.ServerStreamingClient[CertificateUpdate]

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
//
// Agent streams live certificate updates to a workload agent so it rotates without downtime.
type AgentServer interface {
	Watch(*WatchRequest, grpc.ServerStreamingServer[CertificateUpdate]) error
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) Watch(*WatchRequest, grpc.ServerStreamingServer[CertificateUpdate]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).Watch(m, &grpc.GenericServerStream[WatchRequest, CertificateUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_WatchServer = grpc.ServerStreamingServer[CertificateUpdate]

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lcm.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Agent_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lcm/v1/lcm.proto",
}

const (
	Certificates_Download_FullMethodName = "/lcm.v1.Certificates/Download"
)

// CertificatesClient is the client API for Certificates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Certificates lets an authorized platform module fetch an already-issued
// certificate (cert + chain + retained key) for deployment. Module-to-module
// over SPIFFE mTLS, policed by policy.yaml (SR-003); never proxied by the
// gateway. Used by the deployer to install certificates onto infrastructure.
type CertificatesClient interface {
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*CertificateBundle, error)
}

type certificatesClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificatesClient(cc grpc.ClientConnInterface) CertificatesClient {
	return &certificatesClient{cc}
}

func (c *certificatesClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*CertificateBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateBundle)
	err := c.cc.Invoke(ctx, Certificates_Download_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificatesServer is the server API for Certificates service.
// All implementations must embed UnimplementedCertificatesServer
// for forward compatibility.
//
// Certificates lets an authorized platform module fetch an already-issued
// certificate (cert + chain + retained key) for deployment. Module-to-module
// over SPIFFE mTLS, policed by policy.yaml (SR-003); never proxied by the
// gateway. Used by the deployer to install certificates onto infrastructure.
type CertificatesServer interface {
	Download(context.Context, *DownloadRequest) (*CertificateBundle, error)
	mustEmbedUnimplementedCertificatesServer()
}

// UnimplementedCertificatesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCertificatesServer struct{}

func (UnimplementedCertificatesServer) Download(context.Context, *DownloadRequest) (*CertificateBundle, error) {
	return nil, status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedCertificatesServer) mustEmbedUnimplementedCertificatesServer() {}
func (UnimplementedCertificatesServer) testEmbeddedByValue()                      {}

// UnsafeCertificatesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificatesServer will
// result in compilation errors.
type UnsafeCertificatesServer interface {
	mustEmbedUnimplementedCertificatesServer()
}

func RegisterCertificatesServer(s grpc.ServiceRegistrar, srv CertificatesServer) {
	// If the following call panics, it indicates UnimplementedCertificatesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Certificates_ServiceDesc, srv)
}

func _Certificates_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificatesServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Certificates_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificatesServer).Download(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Certificates_ServiceDesc is the grpc.ServiceDesc for Certificates service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Certificates_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lcm.v1.Certificates",
	HandlerType: (*CertificatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Download",
			Handler:    _Certificates_Download_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lcm/v1/lcm.proto",
}
