// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	gocontext "context"

	"github.com/go-kratos/kratos/v2"
	appViewer "github.com/go-tangra/go-tangra-common/viewer"
	bootstrap2 "github.com/go-tangra/go-tangra-lcm/internal/bootstrap"
	"github.com/go-tangra/go-tangra-lcm/internal/cert"
	"github.com/go-tangra/go-tangra-lcm/internal/client"
	"github.com/go-tangra/go-tangra-lcm/internal/data"
	"github.com/go-tangra/go-tangra-lcm/internal/event"
	"github.com/go-tangra/go-tangra-lcm/internal/metrics"
	"github.com/go-tangra/go-tangra-lcm/internal/recipients"
	"github.com/go-tangra/go-tangra-lcm/internal/server"
	"github.com/go-tangra/go-tangra-lcm/internal/service"
	"github.com/go-tangra/go-tangra-lcm/internal/service/providers"
	"github.com/go-tangra/go-tangra-lcm/internal/webhook"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

import (
	_ "github.com/go-tangra/go-tangra-lcm/internal/data/ent/runtime"
	_ "github.com/go-tangra/go-tangra-lcm/pkg/dns/init"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application.
//
// Parameters:
//   - *bootstrap.Context: *bootstrap.Context: bootstrap context
//
// Returns:
//   - *kratos.App: *kratos.App: constructed application instance
//   - func(): func(): cleanup function to run on shutdown
//   - error: error: possible construction error
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	collector := metrics.NewCollector(context)
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	mtlsCertificateRepo := data.NewMtlsCertificateRepo(context, entClient)
	systemService := service.NewSystemService(context)
	lcmClientRepo := data.NewLcmClientRepo(context, entClient)
	clientInstalledCertificateRepo := data.NewClientInstalledCertificateRepo(context, entClient)
	mtlsCertificateRequestRepo := data.NewMtlsCertificateRequestRepo(context, entClient)
	tenantSecretRepo := data.NewTenantSecretRepo(context, entClient)
	redisClient, cleanup2, err := data.NewRedisClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	lcmClientService := service.NewLcmClientService(context, certManager, lcmClientRepo, clientInstalledCertificateRepo, mtlsCertificateRequestRepo, mtlsCertificateRepo, tenantSecretRepo, redisClient, collector)
	issuerRepo := data.NewIssuerRepo(context, entClient)
	issuerService := service.NewIssuerService(context, issuerRepo, lcmClientRepo, mtlsCertificateRepo, collector)
	lcm := providers.ProvideLCMConfig(context)
	issuedCertificateRepo := data.NewIssuedCertificateRepo(context, entClient)
	publisher := event.NewPublisher(context, redisClient)
	registrationClient, err := client.NewRegistrationClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	moduleDialer := client.NewModuleDialer(context, registrationClient)
	notificationClient, cleanup3, err := client.NewNotificationClient(context, moduleDialer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	recipientResolver, cleanupRecipients, err := recipients.NewResolver(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	certificateJobService := service.NewCertificateJobService(context, lcm, issuerRepo, lcmClientRepo, mtlsCertificateRepo, issuedCertificateRepo, publisher, collector, notificationClient, recipientResolver)
	certificateRenewalRepo := data.NewCertificateRenewalRepo(context, entClient)
	deployerClient, cleanup4, err := client.NewDeployerClient(context, registrationClient)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	issuedCertificateService := service.NewIssuedCertificateService(context, issuedCertificateRepo, lcmClientRepo, mtlsCertificateRepo, certificateRenewalRepo, deployerClient)
	tenantSecretService := service.NewTenantSecretService(context, tenantSecretRepo, lcmClientRepo)
	auditLogService := service.NewAuditLogService(context, auditLogRepo, lcmClientRepo)
	mtlsCertService, err := service.NewMtlsCertService(context, mtlsCertificateRepo, lcmClientRepo, collector)
	if err != nil {
		cleanupRecipients()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	certificatePermissionRepo := data.NewCertificatePermissionRepo(context, entClient)
	certificatePermissionService := service.NewCertificatePermissionService(context, certificatePermissionRepo, lcmClientRepo, issuedCertificateRepo)
	mtlsCertificateRequestService, err := service.NewMtlsCertificateRequestService(context, mtlsCertificateRequestRepo, mtlsCertificateRepo, lcmClientRepo, notificationClient, recipientResolver)
	if err != nil {
		cleanupRecipients()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	statisticsService := service.NewStatisticsService(context, statisticsRepo)
	backupService := service.NewBackupService(context, entClient)
	bootstrapService := service.NewBootstrapService(context, lcm, mtlsCertificateRepo, lcmClientRepo)
	grpcServer := server.NewGRPCServer(context, certManager, collector, auditLogRepo, mtlsCertificateRepo, systemService, lcmClientService, issuerService, certificateJobService, issuedCertificateService, tenantSecretService, auditLogService, mtlsCertService, certificatePermissionService, mtlsCertificateRequestService, statisticsService, backupService, bootstrapService)
	signCertificateService := service.NewSignCertificateService(context, lcm, mtlsCertificateRepo, lcmClientRepo, bootstrapService)
	bootstrapGRPCServer := server.NewBootstrapGRPCServer(context, certManager, signCertificateService)
	httpServer := server.NewHTTPServer(context)
	bootstrapBootstrapService, err := bootstrap2.NewBootstrapService(context, mtlsCertificateRepo, lcmClientRepo, issuedCertificateRepo, issuerRepo)
	if err != nil {
		cleanupRecipients()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	renewalConfig := providers.ProvideRenewalConfig(context)
	renewalScheduler := service.NewRenewalScheduler(context, renewalConfig, lcm, issuedCertificateRepo, certificateRenewalRepo, issuerRepo, lcmClientRepo, certificateJobService, publisher)
	webhookService, err := webhook.NewService(context, redisClient)
	if err != nil {
		cleanupRecipients()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	// Seed Prometheus gauges from the DB so /metrics shows real values
	// immediately on boot — without this, the tangra_lcm_* series only
	// materialise on the next cert event and Grafana dashboards look
	// empty after every restart. SystemViewerContext bypasses ent
	// privacy policies for the cross-tenant aggregate queries.
	collector.Seed(appViewer.NewSystemViewerContext(gocontext.Background()), statisticsRepo)

	app := newApp(context, grpcServer, bootstrapGRPCServer, httpServer, bootstrapBootstrapService, renewalScheduler, webhookService)
	return app, func() {
		cleanupRecipients()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
